import {describe,it,expect} from 'vitest';
import {createArjun,arjunReducer,SCENARIOS,label,type ArjunWorld,type Action} from './arjun-world';
const act=(s:ArjunWorld,...actions:Action[])=>actions.reduce(arjunReducer,s);
function first(s=createArjun(),park=true){
 s=act(s,{type:'ask',person:'noor'},{type:'ask',person:'rae'},{type:park?'park':'remove',id:'idea'},{type:'pin',id:'access'},{type:'pin',id:'time'},{type:'select',id:SCENARIOS[s.scenario]!.options.find(o=>o.access&&o.size>=SCENARIOS[s.scenario]!.size&&o.time===SCENARIOS[s.scenario]!.time)!.id},{type:'propose'});return s;
}
function setup(s=first(),owner:'noor'|'rae'='noor',when:'today'|'tomorrow'='today'){
 return act(s,{type:'anchor'},{type:'park',id:'idea'},{type:'owner',person:owner},{type:'when',when},{type:'continue'});
}
function finish(s:ArjunWorld){return act(s,{type:'ask',person:'rae'},{type:'remove',id:'size'},{type:'retrieve',id:'idea'},{type:'select',id:SCENARIOS[s.scenario]!.options.find(o=>o.access&&o.size>=SCENARIOS[s.scenario]!.size&&o.time===SCENARIOS[s.scenario]!.changedTime&&o.feature)!.id},{type:'propose'})}
describe('Arjun shared decisions',()=>{
 it('all three scenarios complete through both park and return-to-notes tactics',()=>{for(let n=0;n<3;n++)for(const park of [true,false]){let s=first(createArjun(n),park);expect(s.phase).toBe('setup');s=finish(setup(s));expect(s.phase).toBe('complete');expect(s.agreement?.task).toBe('confirm')}});
 it('unknown information cannot silently count as evidence',()=>{let s=act(createArjun(),{type:'select',id:'studio'},{type:'propose'});expect(s.phase).toBe('meeting');expect(s.message).toContain('Noor');s=act(s,{type:'ask',person:'noor'},{type:'propose'});expect(s.message).toContain('Rae')});
 it('the three-space limit is recoverable and preserves identity',()=>{let s=act(createArjun(),{type:'ask',person:'noor'},{type:'ask',person:'rae'},{type:'pin',id:'access'},{type:'pin',id:'time'});expect(s.board).toHaveLength(3);expect(s.board).not.toContain('time');s=act(s,{type:'park',id:'idea'},{type:'pin',id:'time'});expect(s.board).toEqual(['size','access','time']);expect(s.parked).toEqual(['idea'])});
 it('wrong proposals give specific feedback without removing clues',()=>{let s=first();s={...s,phase:'meeting'};const board=s.board;s=act(s,{type:'select',id:'garden'},{type:'propose'});expect(s.message).toContain('step-free');expect(s.board).toEqual(board);s=act(s,{type:'select',id:'library'},{type:'propose'});expect(s.message).toContain('time');expect(s.phase).toBe('meeting')});
 it('Rae can decline today; tomorrow and changing owner are valid recoveries',()=>{let s=act(first(),{type:'anchor'},{type:'owner',person:'rae'},{type:'when',when:'today'});expect(s.when).toBeNull();expect(s.message).toContain('Today is full');expect(act(s,{type:'when',when:'tomorrow'},{type:'continue'}).agreement?.owner).toBe('rae');s=act(s,{type:'change-owner'},{type:'owner',person:'noor'},{type:'when',when:'today'},{type:'continue'});expect(s.agreement?.owner).toBe('noor')});
 it('the saved idea and negotiated action survive a changed agenda',()=>{let s=setup(first(),'rae','tomorrow');expect(s.anchor).toBe(true);expect(s.parked).toEqual(['idea']);expect(s.previousOption).toBe('studio');expect(s.known).not.toContain('time');expect(label(s,'time')).toBe('Time?');s=act(s,{type:'ask',person:'rae'});expect(label(s,'time')).toBe('10am');const done=finish(s);expect(done.agreement).toEqual({task:'confirm',option:'library',owner:'rae',when:'tomorrow'});expect(done.board).toContain('idea');expect(done.parked).toEqual([])});
 it('the old proposal cannot complete the new meeting',()=>{let s=setup();s=act(s,{type:'ask',person:'rae'},{type:'remove',id:'size'},{type:'retrieve',id:'idea'},{type:'propose'});expect(s.phase).toBe('revisit');expect(s.message).toContain('quiet space')});
 it('a real capacity constraint can rule out an otherwise accessible option',()=>{let s=first(createArjun(1));s={...s,phase:'meeting'};s=act(s,{type:'select',id:'small'},{type:'propose'});expect(s.message).toContain('everyone');expect(s.phase).toBe('meeting')});
 it('pause, duplicate pins, invalid selections and phase guards preserve state',()=>{let s=createArjun();expect(arjunReducer(s,{type:'continue'})).toEqual(s);expect(arjunReducer(s,{type:'pin',id:'size'})).toEqual(s);expect(arjunReducer(s,{type:'select',id:'missing'})).toEqual(s);s=arjunReducer(s,{type:'pause',value:true});expect(arjunReducer(s,{type:'ask',person:'rae'})).toEqual(s);const done=finish(setup());expect(arjunReducer(done,{type:'remove',id:'idea'})).toEqual(done)});
 it('replay advances the scenario and clears the previous agreement',()=>{const s=arjunReducer(finish(setup()),{type:'restart'});expect(s.scenario).toBe(1);expect(s.agreement).toBeNull();expect(s.phase).toBe('meeting')});
});
