// The game registry: engine configurations (§46: at least 70% of games are configuration). The
// vertical slice (§97) is the first six; thirty-two in all (§95, §104).
// Instructions are the clone's shout — at most three words — and pass the patient rules.
import type { GameDefinition } from "./types";

export const GAMES: readonly GameDefinition[] = [
  // ── Vertical slice (§97) ────────────────────────────────────────────────────────────────────
  { id: "wasps", title: "Wasps", character: "random", engine: "target_swat", mechanic: "tap", instruction: "SWAT!", activeMs: 4000, config: { kind: "target_swat", targets: ["wasp", "wasp", "wasp"] }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "maya_crossing", title: "Maya crossing", character: "maya", engine: "trace_path", mechanic: "trace", instruction: "DRAW A PATH!", activeMs: 6000, config: { kind: "trace_path", hazards: ["bus", "cyclist", "dog", "advert", "roadworks", "a thought"], pathWidth: 44 }, learningLinks: ["lower_sensory_floor", "overwhelm_reset"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "arjun_lock_in", title: "Arjun locks in", character: "arjun", engine: "semantic_filter", mechanic: "tap_filter", instruction: "LOCK IN!", activeMs: 6000, config: { kind: "semantic_filter", relevant: ["brief", "report", "slides", "revenue chart", "roadmap", "agenda"], irrelevant: ["cow", "sheep", "burger", "dinosaur", "spaceship", "surfboard"], nearMiss: ["a research article", "a personal email", "a news story"] }, learningLinks: ["meeting_anchor", "parking_lot_note"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "zoe_dont_send", title: "Zoe, don’t send it", character: "zoe", engine: "inhibition", mechanic: "no_input", instruction: "DON’T!", activeMs: 5000, config: { kind: "inhibition", temptation: "SEND", taunts: ["pulses", "grows", "shakes", "grows arrows", "says PRESS IT"] }, learningLinks: ["pause_before_send"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "mia_why_here", title: "Mia, why are you here?", character: "mia", engine: "object_search", mechanic: "tap", instruction: "WHY ARE YOU HERE?", activeMs: 5000, config: { kind: "object_search", goal: "charger", decoys: ["banana", "sock", "book", "rubber chicken", "tiny horse"], remindBefore: true }, learningLinks: ["external_cue", "put_it_where"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "pancake", title: "Pancake", character: "random", engine: "target_swat", mechanic: "catch", instruction: "CATCH IT!", activeMs: 3500, config: { kind: "target_swat", targets: ["pancake"] }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
  // ── Signature games (§48–§55) ─────────────────────────────────────────────────────────────
  { id: "leo_mosquito", title: "Leo and the mosquito", character: "leo", engine: "target_swat", mechanic: "tap", instruction: "GET IT!", activeMs: 22000, config: { kind: "target_swat", targets: ["mosquito"], escalation: ["smug mosquito", "megaphone", "tiny helicopter", "mosquito orchestra"] }, learningLinks: ["lower_sensory_floor", "sleep_wind_down"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "theo_get_out", title: "Theo, get out", character: "theo", engine: "semantic_filter", mechanic: "tap_filter", instruction: "GET OUT!", activeMs: 6000, config: { kind: "semantic_filter", relevant: ["shoes", "keys", "phone", "door"], irrelevant: ["crooked book", "laundry", "plant", "email", "open drawer", "vacuum"] }, learningLinks: ["reverse_planning", "launch_pad", "transition_reset"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "jax_just_milk", title: "Jax, just milk", character: "jax", engine: "goal_protection", mechanic: "swipe", instruction: "JUST MILK!", activeMs: 6000, config: { kind: "goal_protection", keep: "milk", intruders: ["kayak", "lamp", "cactus", "drone", "waffle maker"] }, learningLinks: ["park_the_idea", "external_cue"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "nina_start_small", title: "Nina starts small", character: "nina", engine: "semantic_filter", mechanic: "tap", instruction: "START SMALL!", activeMs: 5000, config: { kind: "semantic_filter", relevant: ["type ‘Hi’"], irrelevant: ["write the perfect email", "research everything", "reorganise the notes"] }, learningLinks: ["sixty_second_start", "imperfect_first_draft"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "zoe_keyword", title: "Zoe holds the word", character: "zoe", engine: "hold_release", mechanic: "hold_release", instruction: "HOLD IT!", activeMs: 6000, config: { kind: "hold_release", verb: "Hold ‘airport’", releaseAt: "your turn" }, learningLinks: ["hold_the_keyword"], difficulty: { min: 2, max: 8 }, obvious: false },
  { id: "theo_backwards", title: "Theo plans backwards", character: "theo", engine: "rapid_sorting", mechanic: "sequence", instruction: "WORK BACKWARDS!", activeMs: 7000, config: { kind: "rapid_sorting", bins: ["first", "last"], items: [{ label: "arrive 9:00", bin: "last" }, { label: "shoes and keys", bin: "first" }] }, learningLinks: ["reverse_planning"], difficulty: { min: 2, max: 8 }, obvious: false },
  { id: "mia_list", title: "Mia keeps the list", character: "mia", engine: "rapid_sorting", mechanic: "sequence", instruction: "KEEP THEM!", activeMs: 7000, config: { kind: "rapid_sorting", bins: ["on the list", "never said"], items: [{ label: "milk", bin: "on the list" }, { label: "the parcel", bin: "on the list" }, { label: "stamps", bin: "on the list" }, { label: "the post", bin: "never said" }] }, learningLinks: ["external_cue", "put_it_where"], difficulty: { min: 2, max: 8 }, obvious: false },
  { id: "maya_layers", title: "Maya turns one down", character: "maya", engine: "wipe_scrub", mechanic: "wipe", instruction: "CLEAR ONE!", activeMs: 5000, config: { kind: "wipe_scrub", covering: "notifications" }, learningLinks: ["overwhelm_reset"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "leo_lights_out", title: "Leo, lights out", character: "leo", engine: "precision_timing", mechanic: "timing", instruction: "LIGHTS OUT!", activeMs: 6000, config: { kind: "precision_timing", marks: ["10pm", "11pm", "midnight", "1am"], hitIndex: 0 }, learningLinks: ["sleep_wind_down", "brain_dump_bed", "lower_sensory_floor"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "arjun_parking", title: "Arjun parks the thought", character: "arjun", engine: "rapid_sorting", mechanic: "drag", instruction: "PARK IT!", activeMs: 6000, config: { kind: "rapid_sorting", bins: ["LATER", "NOW"], items: [{ label: "buy flights", bin: "LATER" }, { label: "the revenue question", bin: "NOW" }, { label: "that podcast", bin: "LATER" }] }, learningLinks: ["parking_lot_note", "meeting_anchor"], difficulty: { min: 2, max: 8 }, obvious: false },
  // ── Fun games (§56): 20–30% of a run, no learning attached ─────────────────────────────────
  { id: "pigeons", title: "Pigeons", character: "random", engine: "goal_protection", mechanic: "swipe", instruction: "PIGEONS!", activeMs: 5000, config: { kind: "goal_protection", keep: "chips", intruders: ["pigeon", "pigeon", "seagull"] }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "toast", title: "Toast", character: "random", engine: "precision_timing", mechanic: "timing", instruction: "POP IT!", activeMs: 4000, config: { kind: "precision_timing", marks: ["pale", "golden", "dark", "charcoal"], hitIndex: 1 }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "bubbles", title: "Bubbles", character: "random", engine: "target_swat", mechanic: "rapid_tap", instruction: "POP!", activeMs: 4000, config: { kind: "target_swat", targets: ["bubble", "bubble", "bubble", "bubble", "bubble"] }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "spider", title: "Spider", character: "random", engine: "inhibition", mechanic: "no_input", instruction: "STAY STILL!", activeMs: 4000, config: { kind: "inhibition", temptation: "the spider", taunts: ["waves", "waves harder", "brings a friend"] }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "rogue_blender", title: "Rogue blender", character: "random", engine: "hold_release", mechanic: "hold", instruction: "HOLD THE LID!", activeMs: 4500, config: { kind: "hold_release", verb: "Hold", releaseAt: "it stops" }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "office_chair", title: "Runaway office chair", character: "random", engine: "trace_path", mechanic: "trace", instruction: "STEER!", activeMs: 5000, config: { kind: "trace_path", hazards: ["printer", "colleague", "pot plant"], pathWidth: 52 }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
  // ── L5 (§104): toward thirty-two ───────────────────────────────────────────────────────────
  { id: "maya_turn_it_down", title: "Maya turns it down", character: "maya", engine: "wipe_scrub", mechanic: "wipe", instruction: "TURN IT DOWN!", activeMs: 5000, config: { kind: "wipe_scrub", covering: "the noise" }, learningLinks: ["lower_sensory_floor", "overwhelm_reset"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "leo_one_more", title: "Leo, one more scroll", character: "leo", engine: "inhibition", mechanic: "no_input", instruction: "DON’T SCROLL!", activeMs: 5000, config: { kind: "inhibition", temptation: "ONE MORE", taunts: ["glows", "shows a cat", "shows two cats", "says JUST ONE", "says LAST ONE"] }, learningLinks: ["sleep_wind_down", "brain_dump_bed"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "arjun_hold_thread", title: "Arjun holds the thread", character: "arjun", engine: "hold_release", mechanic: "hold_release", instruction: "STAY WITH IT!", activeMs: 6000, config: { kind: "hold_release", verb: "Hold the thread", releaseAt: "the question" }, learningLinks: ["meeting_anchor", "transition_reset", "hold_the_keyword"], difficulty: { min: 2, max: 8 }, obvious: false },
  { id: "zoe_drafts", title: "Zoe deletes the drafts", character: "zoe", engine: "target_swat", mechanic: "rapid_tap", instruction: "DELETE DRAFTS!", activeMs: 4500, config: { kind: "target_swat", targets: ["draft", "draft", "draft", "DRAFT"] }, learningLinks: ["pause_before_send", "park_the_idea"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "theo_shower", title: "Theo, out of the shower", character: "theo", engine: "precision_timing", mechanic: "timing", instruction: "OUT NOW!", activeMs: 6000, config: { kind: "precision_timing", marks: ["5 min", "10 min", "25 min", "an hour"], hitIndex: 1 }, learningLinks: ["reverse_planning"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "mia_the_list", title: "Mia finds the list", character: "mia", engine: "object_search", mechanic: "tap", instruction: "FIND THE LIST!", activeMs: 5000, config: { kind: "object_search", goal: "the list", decoys: ["a receipt", "a leaflet", "a napkin", "the other list", "a menu"], remindBefore: false }, learningLinks: ["external_cue", "put_it_where"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "jax_checkout", title: "Jax at the checkout", character: "jax", engine: "semantic_filter", mechanic: "tap_filter", instruction: "ONLY THE LIST!", activeMs: 6000, config: { kind: "semantic_filter", relevant: ["milk", "bread", "eggs"], irrelevant: ["kayak", "drone", "pizza oven", "lamp", "a second kayak", "bagpipes"], nearMiss: ["oat milk", "a bread maker"] }, learningLinks: ["park_the_idea"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "nina_first_line", title: "Nina writes the line", character: "nina", engine: "trace_path", mechanic: "trace", instruction: "WRITE THE LINE!", activeMs: 6000, config: { kind: "trace_path", hazards: ["rewrite it", "check email", "research more", "reread it", "a better font"], pathWidth: 44 }, learningLinks: ["sixty_second_start", "imperfect_first_draft"], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "sneeze", title: "The sneeze", character: "random", engine: "hold_release", mechanic: "hold", instruction: "HOLD IT IN!", activeMs: 4500, config: { kind: "hold_release", verb: "Hold", releaseAt: "the tissue" }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
  { id: "ducks", title: "Duck or goose", character: "random", engine: "rapid_sorting", mechanic: "sequence", instruction: "DUCK OR GOOSE!", activeMs: 6000, config: { kind: "rapid_sorting", bins: ["duck", "goose"], items: [{ label: "quack", bin: "duck" }, { label: "honk", bin: "goose" }, { label: "small, quacking", bin: "duck" }, { label: "hissing at you", bin: "goose" }, { label: "wants your chips", bin: "goose" }] }, learningLinks: [], difficulty: { min: 1, max: 8 }, obvious: true },
];

export function game(id: string): GameDefinition {
  const g = GAMES.find((x) => x.id === id);
  if (!g) throw new Error(`lives: unknown game ${id}`);
  return g;
}

/** §97: the six the whole flow must work across before content grows. */
export const VERTICAL_SLICE_GAME_IDS = ["wasps", "maya_crossing", "arjun_lock_in", "zoe_dont_send", "mia_why_here", "pancake"] as const;
