// §96: the initial module register as strategy records (§23). Every strategy is independent of the
// game; §79 tone in every claim; §77 review status carried, pending until a clinician has read it.
import type { StrategyDefinition } from "./types";

export const STRATEGIES: readonly StrategyDefinition[] = [
  { id: "meeting_anchor", title: "Meeting Anchor", shortDescription: "Give drifting attention somewhere physical to return to.", domains: ["attention", "working_memory"], estimatedMinutes: 2, characterIds: ["arjun"], relatedGameIds: ["arjun_lock_in", "arjun_parking", "arjun_hold_thread"], evidenceLevel: "practical_consensus", moduleId: "meeting_anchor_v1", tags: ["work", "meetings", "2-minute"], active: true, claim: "An external attention anchor may help some people return attention to the task.", reviewStatus: "pending" },
  { id: "parking_lot_note", title: "Parking Lot Note", shortDescription: "One note labelled LATER for every thought that is not this meeting.", domains: ["attention", "working_memory"], estimatedMinutes: 2, characterIds: ["arjun"], relatedGameIds: ["arjun_parking", "arjun_lock_in"], evidenceLevel: "practical_consensus", moduleId: "parking_lot_note_v1", tags: ["work", "meetings", "2-minute"], active: true, claim: "Writing an unrelated thought down can let some people return to what they were doing.", reviewStatus: "pending" },
  { id: "external_cue", title: "Why Am I Here? External Cue", shortDescription: "Say the errand out loud, or carry the thing it is for.", domains: ["working_memory", "environment"], estimatedMinutes: 3, characterIds: ["mia"], relatedGameIds: ["mia_why_here", "mia_list", "mia_the_list"], evidenceLevel: "practical_consensus", moduleId: "external_cue_v1", tags: ["home", "memory", "2-minute"], active: true, claim: "A cue outside the head can carry an intention through a doorway for some people.", reviewStatus: "pending" },
  { id: "put_it_where", title: "Put It Where You’ll Need It", shortDescription: "Convert an intention into an object in the place it is needed.", domains: ["working_memory", "environment", "organisation"], estimatedMinutes: 2, characterIds: ["mia"], relatedGameIds: ["mia_why_here", "mia_the_list"], evidenceLevel: "practical_consensus", moduleId: "put_it_where_v1", tags: ["home", "memory"], active: true, claim: "Context-linked cues are noticed where invisible reminders are not, for some people.", reviewStatus: "pending" },
  { id: "reverse_planning", title: "Reverse Planning", shortDescription: "Plan from arrival backwards instead of estimating forwards.", domains: ["time_management", "planning", "transitions"], estimatedMinutes: 4, characterIds: ["theo"], relatedGameIds: ["theo_get_out", "theo_backwards", "theo_shower"], evidenceLevel: "practical_consensus", moduleId: "reverse_planning_v1", tags: ["time", "leaving"], active: true, claim: "Working backwards from an arrival time can make a departure time visible.", reviewStatus: "pending" },
  { id: "launch_pad", title: "Launch Pad", shortDescription: "Keys, wallet, badge: one place by the door.", domains: ["environment", "transitions", "organisation"], estimatedMinutes: 3, characterIds: ["theo", "mia"], relatedGameIds: ["theo_get_out"], evidenceLevel: "practical_consensus", moduleId: "launch_pad_v1", tags: ["home", "leaving", "environment"], active: true, claim: "A fixed place for leaving things can remove a search from every departure.", reviewStatus: "pending" },
  { id: "sixty_second_start", title: "60-Second Start", shortDescription: "Make the first step embarrassingly small, then do sixty seconds of it.", domains: ["task_initiation"], estimatedMinutes: 2, characterIds: ["nina"], relatedGameIds: ["nina_start_small", "nina_first_line"], evidenceLevel: "supported", moduleId: "sixty_second_start_v1", tags: ["starting", "2-minute", "work", "study"], active: true, claim: "A very small first physical action lowers the threshold to begin for many people.", reviewStatus: "pending" },
  { id: "imperfect_first_draft", title: "Imperfect First Draft", shortDescription: "Write it badly on purpose; fix it later.", domains: ["task_initiation", "emotional_regulation"], estimatedMinutes: 3, characterIds: ["nina"], relatedGameIds: ["nina_start_small", "nina_first_line"], evidenceLevel: "practical_consensus", moduleId: "imperfect_first_draft_v1", tags: ["starting", "perfectionism", "work"], active: true, claim: "Permission to be rough can unstick a start that a high standard was blocking.", reviewStatus: "pending" },
  { id: "pause_before_send", title: "Pause Before Send", shortDescription: "Draft it. Wait. Then decide.", domains: ["impulsivity", "communication", "emotional_regulation"], estimatedMinutes: 3, characterIds: ["zoe", "jax"], relatedGameIds: ["zoe_dont_send", "zoe_drafts"], evidenceLevel: "practical_consensus", moduleId: "pause_before_send_v1", tags: ["messages", "relationships", "2-minute"], active: true, claim: "A short delay before an emotionally loaded reply can give the first reaction time to settle.", reviewStatus: "pending" },
  { id: "hold_the_keyword", title: "Hold the Keyword", shortDescription: "Keep one word, not the whole sentence, and go back to listening.", domains: ["communication", "relationships", "working_memory"], estimatedMinutes: 4, characterIds: ["zoe"], relatedGameIds: ["zoe_keyword"], evidenceLevel: "practical_consensus", moduleId: "hold_the_keyword_v1", tags: ["conversations", "relationships"], active: true, claim: "Holding one keyword can keep a thought without interrupting, for some people.", reviewStatus: "pending" },
  { id: "lower_sensory_floor", title: "Lower the Sensory Floor", shortDescription: "Add a predictable background so tiny noises stop being the loudest thing.", domains: ["sensory_management", "sleep"], estimatedMinutes: 3, characterIds: ["maya", "leo"], relatedGameIds: ["leo_mosquito", "maya_crossing", "maya_turn_it_down"], evidenceLevel: "experiential", moduleId: "lower_sensory_floor_v1", tags: ["sleep", "sensory", "home"], active: true, claim: "A predictable background sound may make individual noises less salient for some people.", reviewStatus: "pending" },
  { id: "overwhelm_reset", title: "Overwhelm Reset", shortDescription: "Remove one layer instead of forcing perfect concentration.", domains: ["sensory_management", "emotional_regulation", "mindfulness"], estimatedMinutes: 3, characterIds: ["maya"], relatedGameIds: ["maya_crossing", "maya_layers", "maya_turn_it_down"], evidenceLevel: "practical_consensus", moduleId: "overwhelm_reset_v1", tags: ["overwhelm", "sensory", "3-minute"], active: true, claim: "Reducing total input can be easier than concentrating harder against it, for some people.", reviewStatus: "pending" },
  { id: "sleep_wind_down", title: "Sleep Wind-Down", shortDescription: "A five-minute settle for a brain that is still going.", domains: ["sleep", "mindfulness"], estimatedMinutes: 5, characterIds: ["leo"], relatedGameIds: ["leo_mosquito", "leo_lights_out", "leo_one_more"], evidenceLevel: "supported", moduleId: "sleep_wind_down_v1", tags: ["sleep", "audio", "evening"], active: true, claim: "A short, repeatable wind-down can lower arousal before sleep for many people.", reviewStatus: "pending" },
  { id: "brain_dump_bed", title: "Brain Dump Before Bed", shortDescription: "Write down what your brain is trying not to forget, then let it.", domains: ["sleep", "working_memory"], estimatedMinutes: 3, characterIds: ["leo", "mia"], relatedGameIds: ["leo_lights_out", "leo_one_more"], evidenceLevel: "practical_consensus", moduleId: "brain_dump_bed_v1", tags: ["sleep", "memory", "evening"], active: true, claim: "Externalising tomorrow's list before bed can quiet the rehearsing that keeps some people awake.", reviewStatus: "pending" },
  { id: "park_the_idea", title: "Park the New Idea", shortDescription: "Capture it, date it, come back in a day.", domains: ["impulsivity", "prioritisation", "planning"], estimatedMinutes: 2, characterIds: ["jax"], relatedGameIds: ["jax_just_milk", "jax_checkout"], evidenceLevel: "practical_consensus", moduleId: "park_the_idea_v1", tags: ["money", "ideas", "2-minute"], active: true, claim: "A day between wanting and buying may keep the good ideas and lose most of the rest.", reviewStatus: "pending" },
  { id: "transition_reset", title: "3-Minute Transition Reset", shortDescription: "A short reset between one thing and the next.", domains: ["transitions", "mindfulness"], estimatedMinutes: 3, characterIds: ["maya", "leo", "arjun", "zoe", "theo", "mia", "jax", "nina"], relatedGameIds: ["arjun_hold_thread"], evidenceLevel: "experiential", moduleId: "transition_reset_v1", tags: ["transitions", "audio", "3-minute"], active: true, claim: "Some people find a brief grounding useful for resetting attention between tasks.", reviewStatus: "pending" },
];

export function strategy(id: string): StrategyDefinition {
  const s = STRATEGIES.find((x) => x.id === id);
  if (!s) throw new Error(`lives: unknown strategy ${id}`);
  return s;
}

/** §97: the four the whole flow must work across. */
export const VERTICAL_SLICE_STRATEGY_IDS = ["meeting_anchor", "external_cue", "pause_before_send", "lower_sensory_floor"] as const;
