import { describe,it,expect } from 'vitest';
import { createZoe,zoeReducer,SCENARIOS,type ZoeWorld,type ZoeAction } from './zoe-world';
function act(s:ZoeWorld,...actions:ZoeAction[]){return actions.reduce(zoeReducer,s)}
function propose(s=createZoe(),time:18|19|20=19){return act(s,{type:'fact',value:'uncertain'},{type:'need',value:'notice'},{type:'plan',value:'together'},{type:'time',value:time},{type:'send'})}
describe('Zoe reciprocal plans',()=>{
 it('accepts two tactics in all three scenarios',()=>{for(let i=0;i<3;i++){const time=SCENARIOS[i]!.available[0];expect(propose(createZoe(i),time).phase).toBe('setup');const known=act(createZoe(i),{type:'ask'},{type:'fact',value:'changed'},{type:'need',value:'company'},{type:'plan',value:'call'},{type:'time',value:time},{type:'send'});expect(known.phase).toBe('setup')}});
 it('partner availability matters and a declined plan can be revised',()=>{let s=propose(createZoe(),18);expect(s.phase).toBe('conversation');expect(s.known).toBe(true);s=act(s,{type:'time',value:19},{type:'send'});expect(s.phase).toBe('setup');expect(s.attempts).toBe(2)});
 it('does not manufacture certainty and assumptions can be corrected',()=>{let s=act(createZoe(),{type:'fact',value:'changed'});expect(s.draft.fact).toBeNull();s=act(s,{type:'fact',value:'assumed'},{type:'need',value:'space'},{type:'plan',value:'separate'},{type:'send'});expect(s.phase).toBe('conversation');s=act(s,{type:'fact',value:'changed'},{type:'send'});expect(s.phase).toBe('setup')});
 it('a sharp message is recoverable, without automatic forgiveness',()=>{let s=propose(act(createZoe(),{type:'sharp'}));expect(s.phase).toBe('conversation');s=act(s,{type:'repair'},{type:'send'});expect(s.phase).toBe('setup')});
 it('draft survives a pause and saving; paused actions cannot change facts',()=>{let s=act(createZoe(),{type:'need',value:'space'},{type:'save'},{type:'pause',value:true});expect(zoeReducer(s,{type:'sharp'})).toEqual(s);s=zoeReducer(s,{type:'pause',value:false});expect(s.saved).toBe(true);expect(s.draft.need).toBe('space')});
 it('requires actual strategy setup and preserves it through a changed encounter',()=>{let s=propose();expect(zoeReducer(s,{type:'tomorrow'}).phase).toBe('setup');expect(zoeReducer(s,{type:'cue',value:'calendar'}).agreement?.cue).toBeNull();s=act(s,{type:'owner',value:'rae'},{type:'cue',value:'phone'},{type:'tomorrow'});expect(s.phase).toBe('revisit');s=zoeReducer(s,{type:'adjust'});expect(s.agreement).toEqual({owner:'rae',cue:'phone',plan:'together',time:20});expect(s.phase).toBe('complete')});
 it('respects separate plans without a failure state',()=>{let s=act(propose(),{type:'owner',value:'zoe'},{type:'cue',value:'calendar'},{type:'tomorrow'},{type:'boundary'});expect(s.outcome).toBe('boundary');expect(s.agreement?.plan).toBe('separate');expect(s.phase).toBe('complete');expect(zoeReducer(s,{type:'send'})).toEqual(s);expect(zoeReducer(s,{type:'restart'}).scenario).toBe(1)});
 it('saved draft is a snapshot, and a late request respects Rae’s limited capacity',()=>{let s=act(createZoe(),{type:'need',value:'notice'},{type:'save'},{type:'need',value:'space'},{type:'restore'});expect(s.draft.need).toBe('notice');s=propose(s,20);expect(s.phase).toBe('conversation');expect(s.message).toContain('short call');s=act(s,{type:'plan',value:'call'},{type:'send'});expect(s.phase).toBe('setup')});
 it('cannot skip the encounter with out-of-phase setup actions',()=>{const s=createZoe();for(const a of [{type:'tomorrow'},{type:'adjust'},{type:'owner',value:'rae'},{type:'cue',value:'phone'}] as ZoeAction[])expect(zoeReducer(s,a)).toEqual(s)});
});
