import {test,expect} from './support/test';
import {expectNoViolations} from './support/a11y';
import type {Page} from '@playwright/test';
test.setTimeout(90000);
const URL='/lives/play/arjun-hold-the-thread';
async function click(page:Page,name:string){await page.getByRole('button',{name,exact:true}).click()}
async function first(page:Page){for(const name of ['Ask Noor','Ask Rae','Pin Step-free','Park idea','Pin 2pm','Options','Choose Studio','Connect the plan'])await click(page,name);await expect(page.locator('.aw-game')).toHaveAttribute('data-phase','setup')}
async function setup(page:Page){for(const name of ['Pin the question','Rae','Today'])await click(page,name);await expect(page.getByRole('status')).toContainText('Today is full');await click(page,'Tomorrow');await click(page,'Next meeting')}
async function finish(page:Page){for(const name of ['Ask Rae','Return 6 people to notes','Retrieve A quiet break','Options','Choose Library','Connect the plan'])await click(page,name);await expect(page.locator('.aw-game')).toHaveAttribute('data-phase','complete')}
test('library entry, negotiated ownership and retrieved idea complete a changed meeting',async({page})=>{await page.goto('/lives/characters');await page.getByRole('link',{name:'Play Arjun’s moment →',exact:true}).click();await expect(page).toHaveURL(new RegExp(URL));await expect(page.getByRole('slider')).toHaveCount(0);await expect(page.locator('.tm-game,.mt-board')).toHaveCount(0);await first(page);await setup(page);await expect(page.getByText('Time?',{exact:true})).toBeVisible();await finish(page);await expect(page.locator('.aw-agreement')).toContainText('Rae · tomorrow');await expect(page.locator('.aw-agreement')).toContainText('Confirm Library');await expect(page.getByRole('link',{name:'Try a meeting anchor'})).toHaveAttribute('href','/lives/learn?module=meeting_anchor_v1');await click(page,'Another meeting');await expect(page.locator('.aw-game')).toHaveAttribute('data-scenario','1')});
test('full board, incompatible choices and pause are recoverable',async({page})=>{await page.goto(URL);for(const name of ['Ask Noor','Ask Rae','Pin Step-free','Pin 2pm'])await click(page,name);await expect(page.getByRole('status')).toContainText('Three spaces full');await click(page,'Park idea');await click(page,'Pin 2pm');await click(page,'Options');await click(page,'Choose Garden');await click(page,'Connect the plan');await expect(page.getByRole('status')).toContainText('step-free');const before=await page.locator('.aw-card').allTextContents();await click(page,'Pause game');await expect(page.getByRole('group',{name:'Three working spaces'})).toHaveCount(0);await click(page,'Resume');expect(await page.locator('.aw-card').allTextContents()).toEqual(before);await click(page,'Choose Studio');await click(page,'Connect the plan');await expect(page.locator('.aw-game')).toHaveAttribute('data-phase','setup')});
test('responsive table, reachable exit and four accessible phases',async({page},info)=>{await page.emulateMedia({reducedMotion:'reduce'});for(const [width,height] of [[320,568],[390,844],[844,390],[1440,1000]] as const){await page.setViewportSize({width,height});await page.goto(URL);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));expect(await page.getByRole('link',{name:'Back to games'}).evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))})).toBe(true);await page.getByRole('link',{name:'Back to games'}).click()}
await page.setViewportSize({width:390,height:844});await page.goto(URL);await expectNoViolations(page,'Arjun meeting');if(info.project.name==='chromium')await page.screenshot({path:'qa/_runs/arjun-phone.png',fullPage:true});await first(page);await expectNoViolations(page,'Arjun setup');await setup(page);await expectNoViolations(page,'Arjun revisit');await finish(page);await expectNoViolations(page,'Arjun completion')});
test('touch-only meeting and keyboard notes do not create health inferences',async({browser,baseURL})=>{const c=await browser.newContext({baseURL,viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'});await c.addInitScript(()=>localStorage.setItem('adhdme-privacy-ack','1'));const page=await c.newPage();await page.goto(URL);const before=await page.evaluate(()=>JSON.stringify(localStorage));await page.getByRole('button',{name:'Ask Noor',exact:true}).focus();await page.keyboard.press('Enter');for(const name of ['Ask Rae','Pin Step-free','Park idea','Pin 2pm','Options','Choose Studio','Connect the plan','Pin the question','Noor','Today','Next meeting','Ask Rae','Return 6 people to notes','Retrieve A quiet break','Options','Choose Library','Connect the plan'])await page.getByRole('button',{name,exact:true}).tap();await expect(page.locator('.aw-game')).toHaveAttribute('data-phase','complete');expect(await page.evaluate(()=>JSON.stringify(localStorage))).toBe(before);await c.close()});
