// O217: the synthetic example roster — invented GP profiles the finder can OPT INTO for testing.
//
// FOUNDER DECISION `synthetic-roster-tickbox` (src/design/founder-gates.ts, 2026-09-01) is the
// authority for this file's existence: the persona purge made the `clinicians` roster
// real-people-only, and the founder has asked for example profiles back — in the live finder,
// behind a reader-visible tickbox, this deployment only, because "this finder system of the
// adhdme repo is not public so it's ok it's just for testing".
//
// WHAT KEEPS THIS FROM BEING THE THING THE PURGE REMOVED. The purge's harm was invented detail
// PRESENTED AS REAL: fabricated availability under plausible names, bookable-looking mocks.
// Every line of defence here is against that, and `synthetic-roster.test.ts` enforces each:
//   * `synthetic: true` on every entry, never `realPerson` — the surfaces read the flag and say
//     "Example profile" out loud wherever one renders;
//   * `image: null` always — the monogram renders; nothing generates a face, because a generated
//     face IS a fabricated person presented as genuine;
//   * `booking.via: "synthetic-none"` with no url — there is nobody to book and no control that
//     pretends otherwise;
//   * practice names self-mark ("… Example Practice" / "… Example Clinic"), so no invented name can collide with
//     a real business;
//   * no `disclosedInterest` — an invented conflict is still an invented claim, and the
//     founder-behind ranking laws stay testable against real data only;
//   * every rendered string passes the same patient-surface linter as real copy — invented does
//     not mean exempt, it renders to the same reader;
//   * the `clinicians` export, ROSTER_SIZE, the coverage map and every public count stay
//     real-only: this list reaches a ranking ONLY through the finder's tickbox.
//
// THIS IS NOT `syntheticClinician()` (synthetic-clinician.ts) AND MUST NOT MERGE WITH IT. That
// template is the engine tests' neutral blank and its own law says it never reaches a surface;
// these personas exist to reach one. Coupling them would put fifty ranking laws back at the
// mercy of somebody editing a persona for looks — the exact tangle W193/O179 untied.
//
// WHY THE SET LOOKS THE WAY IT DOES. Twenty personas (founder follow-up, same day: "Let's put
// in 20 synthetic profiles"), designed rather than sampled: together with the two real GPs they
// cover every `CareArea` in the closed vocabulary AND every language in `MATCHABLE_LANGUAGES`,
// all three genders, every manner facet, four closed books (the closed-outranks-nothing law
// visible in more than one suburb), stale and fresh capacity declarations (all three O56
// freshness grades render), and four telehealth-first entries (the distance law's exception
// exercised). Suburbs are real gazetteer rows so computed distance works — a suburb is a
// place, not a person, and inventing one would break the arithmetic without protecting
// anybody.

import type { Clinician } from "./roster";
import { clinicians } from "./roster";

/** The one sentence every persona's `about` must end with — the census pins its presence. */
export const SYNTHETIC_ABOUT_NOTICE =
  "This is a fictional example profile used for trying the finder. It describes nobody.";

/** The shared booking explanation — the census pins that no persona carries anything else. */
export const SYNTHETIC_BOOKING_NOTE =
  "This is an example profile used for trying the finder. There is nobody to book.";

export const SYNTHETIC_CLINICIANS: readonly Clinician[] = [
  {
    id: "example-mei-chao",
    name: "Dr Mei Chao",
    shortName: "Dr Chao",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Epping",
    practice: "Epping Example Practice",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-25",
    focus: "ADHD assessment across ages, titration",
    matchLine: "Says she sees ADHD assessment often, for adults and for school-age patients, with titration reviewed on a schedule.",
    fitSignals: ["ADHD assessment", "Children and adolescents", "Titration", "Mandarin"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Mei says she sees ADHD assessment often, in adults and in children and adolescents, and reviews titration on a set schedule. She consults in English and Mandarin.",
    about:
      `Mei is an invented example GP. Her profile declares frequent adult and child ADHD assessment, scheduled titration review, and consultations in English and Mandarin. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Structured adult ADHD assessment", "Child and adolescent assessment", "Titration and scheduled review"],
    languages: ["English", "Mandarin"],
    careAreas: ["adhd-assessment", "child-adolescent-adhd", "titration"],
    manner: ["unhurried", "collaborative"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-tomas-rivera",
    name: "Dr Tomás Rivera",
    shortName: "Dr Rivera",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MD FRACGP",
    suburb: "Bondi Junction",
    practice: "Bondi Junction Example Practice",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    // Stale on purpose: an open declaration past the 90-day freshness window, so the
    // stale-open capacity grade renders somewhere a tester can see it.
    capacityDeclaredAt: "2026-04-02",
    focus: "ADHD assessment alongside low mood and anxiety",
    matchLine: "Says he often sees ADHD questions that arrive together with low mood or anxiety.",
    fitSignals: ["ADHD assessment", "Low mood", "Anxiety", "Spanish"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Tomás says he often sees ADHD questions that arrive together with low mood or anxiety, and works out with the patient which thread to pull first. He consults in English and Spanish.",
    about:
      `Tomás is an invented example GP. His profile declares frequent ADHD assessment alongside depression and anxiety care, and consultations in English and Spanish. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Depression and anxiety care in general practice"],
    languages: ["English", "Spanish"],
    careAreas: ["adhd-assessment", "depression", "anxiety"],
    manner: ["attuned", "non_judgmental"],
    wheelchairAccessible: true,
    appointmentLength: "Appointment lengths set with the practice",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-priya-nair",
    name: "Dr Priya Nair",
    shortName: "Dr Nair",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP DCH",
    suburb: "Hornsby",
    practice: "Hornsby Example Practice",
    reach: "Practice appointments",
    image: null,
    // Closed books: the closed-never-outranks-open-at-equal-fit law, visible to a tester.
    acceptingNewPatients: false,
    capacityDeclaredAt: "2026-08-20",
    focus: "ADHD and autism presenting together, non-medication supports",
    matchLine: "Says she often sees ADHD and autism presenting together, and gives the non-medication half of a plan real room.",
    fitSignals: ["ADHD assessment", "Autism and ADHD", "Non-medication supports", "Malayalam"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Priya says she often sees co-occurring ADHD and autism, and puts as much of the plan into non-medication supports as into anything else. She consults in English and Malayalam.",
    about:
      `Priya is an invented example GP. Her profile declares frequent co-occurring ADHD and autism work and non-medication supports, and consultations in English and Malayalam. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Co-occurring autism and ADHD", "Non-medication and psychological supports"],
    languages: ["English", "Malayalam"],
    careAreas: ["adhd-assessment", "autism-adhd", "non-medication"],
    manner: ["sense_making", "collaborative"],
    wheelchairAccessible: false,
    appointmentLength: "Long first appointment",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-owen-hartley",
    name: "Dr Owen Hartley",
    shortName: "Dr Hartley",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Southport",
    practice: "Southport Example Practice",
    reach: "Telehealth and practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-28",
    focus: "Structured assessment, titration, substance history taken seriously",
    matchLine: "Says he works from a documented baseline, reviews titration on a schedule, and takes a substance history as a safety question.",
    fitSignals: ["ADHD assessment", "Titration", "Substance history", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary:
      "Owen says he works from a documented baseline, reviews titration on a schedule, and takes a substance history as a safety question rather than a judgement. First appointments can be by telehealth.",
    about:
      `Owen is an invented example GP. His profile declares structured assessment, scheduled titration review, substance-history care, and telehealth-first appointments. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Structured adult ADHD assessment", "Titration and scheduled review", "Substance-history care in general practice"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "titration", "substance-history"],
    manner: ["structured", "steadying"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment, scheduled reviews",
    telehealthFirstAppointment: true,
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-sarah-whitfield",
    name: "Dr Sarah Whitfield",
    shortName: "Dr Whitfield",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Pennant Hills",
    practice: "Pennant Hills Example Practice",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-22",
    focus: "Trauma-aware assessment, emotional regulation",
    matchLine: "Says she often sees emotional regulation and rejection sensitivity first, and takes assessment at a trauma-aware pace.",
    fitSignals: ["ADHD assessment", "Emotional regulation", "Trauma-aware care"],
    practicalSignals: ["Mixed billing", "Extended first appointment"],
    summary:
      "Sarah says the thing she hears first is often emotional regulation and rejection sensitivity, and that she takes assessment at a trauma-aware pace with time to be heard.",
    about:
      `Sarah is an invented example GP. Her profile declares trauma-aware ADHD assessment and frequent emotional-regulation work. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Trauma-aware general practice", "Emotional regulation and rejection sensitivity"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "emotional-regulation", "trauma-informed"],
    manner: ["attuned", "steadying", "non_judgmental"],
    wheelchairAccessible: true,
    appointmentLength: "Extended first appointment",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-daniel-okafor",
    name: "Dr Daniel Okafor",
    shortName: "Dr Okafor",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Surfers Paradise",
    practice: "Surfers Paradise Example Practice",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    // Stale on purpose — the second stale-open grade, so the state is not a single row's quirk.
    capacityDeclaredAt: "2026-03-15",
    focus: "Shared care, complex presentations held with their psychiatrist",
    matchLine: "Says he often carries GP shared care under a psychiatrist's plan, including complex presentations.",
    fitSignals: ["ADHD assessment", "Shared care", "Complex presentations", "Igbo"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Daniel says he often carries GP shared care under a psychiatrist's or paediatrician's plan, including bipolar and other complex presentations held with their psychiatrist and team. He consults in English and Igbo.",
    about:
      `Daniel is an invented example GP. His profile declares frequent shared-care arrangements and complex presentations held with their psychiatrist, and consultations in English and Igbo. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["GP shared care under psychiatrist plans", "Complex presentations held with their psychiatrist and team"],
    languages: ["English", "Igbo"],
    careAreas: ["adhd-assessment", "shared-care", "complex-mental-health"],
    manner: ["sense_making", "structured"],
    wheelchairAccessible: true,
    appointmentLength: "Appointment lengths set with the practice",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-hana-yoshida",
    name: "Dr Hana Yoshida",
    shortName: "Dr Yoshida",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Rose Bay",
    practice: "Rose Bay Example Practice",
    reach: "Practice appointments",
    image: null,
    // The second closed-books entry, so closed rows appear in more than one suburb.
    acceptingNewPatients: false,
    capacityDeclaredAt: "2026-08-10",
    focus: "ADHD assessment alongside anxiety, non-medication supports",
    matchLine: "Says she often sees anxiety and ADHD presenting through each other, with unhurried appointments and non-medication supports in the plan.",
    fitSignals: ["ADHD assessment", "Anxiety", "Non-medication supports", "Vietnamese"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Hana says she often sees anxiety and ADHD presenting through each other, keeps first appointments unhurried, and gives non-medication supports real room in the plan. She consults in English and Vietnamese.",
    about:
      `Hana is an invented example GP. Her profile declares frequent anxiety-and-ADHD work, unhurried appointments and non-medication supports, and consultations in English and Vietnamese. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Anxiety care in general practice", "Non-medication and psychological supports"],
    languages: ["English", "Vietnamese"],
    careAreas: ["adhd-assessment", "anxiety", "non-medication"],
    careAreasSometimes: ["depression"],
    manner: ["unhurried", "culturally_attuned"],
    wheelchairAccessible: false,
    appointmentLength: "Long first appointment",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-ash-coleman",
    name: "Dr Ash Coleman",
    shortName: "Dr Coleman",
    gender: "non-binary",
    pronouns: "they/them",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Robina",
    practice: "Robina Example Practice",
    reach: "Telehealth and practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-27",
    focus: "ADHD assessment, low mood, emotional regulation",
    matchLine: "Says they often see ADHD alongside low mood and emotional regulation, and decide the plan with the patient.",
    fitSignals: ["ADHD assessment", "Low mood", "Emotional regulation", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary:
      "Ash says they often see ADHD alongside low mood and emotional-regulation questions, work from strengths, and decide the plan with the patient rather than for them. First appointments can be by telehealth.",
    about:
      `Ash is an invented example GP. Their profile declares frequent ADHD, low-mood and emotional-regulation work, collaborative planning, and telehealth-first appointments. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Depression care in general practice", "Emotional regulation and rejection sensitivity"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "depression", "emotional-regulation"],
    manner: ["collaborative", "motivating"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment",
    telehealthFirstAppointment: true,
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-leila-haddad",
    name: "Dr Leila Haddad",
    shortName: "Dr Haddad",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Edgecliff",
    practice: "Edgecliff Example Practice",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-26",
    focus: "ADHD assessment alongside anxiety, emotional regulation",
    matchLine: "Says she often sees anxiety and emotional-regulation questions arrive first, and keeps the room settled while the assessment takes its course.",
    fitSignals: ["ADHD assessment", "Anxiety", "Emotional regulation", "Arabic"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Leila says anxiety and emotional-regulation questions are often what she hears first, and that she keeps the room settled while an assessment takes its course. She consults in English and Arabic.",
    about:
      `Leila is an invented example GP. Her profile declares frequent anxiety and emotional-regulation work alongside ADHD assessment, and consultations in English and Arabic. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Anxiety care in general practice", "Emotional regulation and rejection sensitivity"],
    languages: ["English", "Arabic"],
    careAreas: ["adhd-assessment", "anxiety", "emotional-regulation"],
    manner: ["attuned", "steadying"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-gurpreet-singh",
    name: "Dr Gurpreet Singh",
    shortName: "Dr Singh",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Cheltenham",
    practice: "Cheltenham Example Practice",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-24",
    focus: "Structured assessment, titration, shared care",
    matchLine: "Says he works to a documented plan, reviews titration at set intervals, and often carries shared care under a psychiatrist's plan.",
    fitSignals: ["ADHD assessment", "Titration", "Shared care", "Punjabi"],
    practicalSignals: ["Mixed billing", "Structured review schedule"],
    summary:
      "Gurpreet says he works to a documented plan, reviews titration at set intervals, and often carries GP shared care under a psychiatrist's plan. He consults in English and Punjabi.",
    about:
      `Gurpreet is an invented example GP. His profile declares structured assessment, scheduled titration review, shared-care arrangements, and consultations in English and Punjabi. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Structured adult ADHD assessment", "Titration and scheduled review", "GP shared care under psychiatrist plans"],
    languages: ["English", "Punjabi"],
    careAreas: ["adhd-assessment", "titration", "shared-care"],
    manner: ["structured", "collaborative"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment, scheduled reviews",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-annika-larsen",
    name: "Dr Annika Larsen",
    shortName: "Dr Larsen",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP DCH",
    suburb: "Broadbeach",
    practice: "Broadbeach Example Practice",
    reach: "Practice appointments",
    image: null,
    // The third closed-books entry — closed rows on the Gold Coast side of the map too.
    acceptingNewPatients: false,
    capacityDeclaredAt: "2026-08-15",
    focus: "ADHD assessment in children and adolescents, non-medication supports",
    matchLine: "Says she often assesses school-age patients, with the non-medication half of the plan given real room.",
    fitSignals: ["ADHD assessment", "Children and adolescents", "Non-medication supports"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Annika says much of her ADHD work is with children and adolescents, run through school as well as home, and that non-medication supports get as much of the plan as anything else.",
    about:
      `Annika is an invented example GP. Her profile declares frequent child and adolescent ADHD assessment and non-medication supports. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Child and adolescent ADHD assessment", "Non-medication and psychological supports"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "child-adolescent-adhd", "non-medication"],
    manner: ["unhurried", "motivating"],
    wheelchairAccessible: true,
    appointmentLength: "Extended first appointment",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-rohan-pillai",
    name: "Dr Rohan Pillai",
    shortName: "Dr Pillai",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Beecroft",
    practice: "Beecroft Example Practice",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    // Stale on purpose — a third stale-open declaration, in a suburb a real GP also consults.
    capacityDeclaredAt: "2026-05-10",
    focus: "ADHD assessment alongside low mood, substance history taken seriously",
    matchLine: "Says he often sees low mood arrive with an ADHD question, and takes a substance history as a safety question rather than a judgement.",
    fitSignals: ["ADHD assessment", "Low mood", "Substance history", "Tamil"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Rohan says low mood often arrives with the ADHD question, and that he takes a substance history as a safety question rather than a judgement. He consults in English and Tamil.",
    about:
      `Rohan is an invented example GP. His profile declares frequent ADHD-and-depression work, substance-history care, and consultations in English and Tamil. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Depression care in general practice", "Substance-history care in general practice"],
    languages: ["English", "Tamil"],
    careAreas: ["adhd-assessment", "depression", "substance-history"],
    manner: ["non_judgmental", "sense_making"],
    wheelchairAccessible: false,
    appointmentLength: "Appointment lengths set with the practice",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-chloe-bennett",
    name: "Dr Chloe Bennett",
    shortName: "Dr Bennett",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Double Bay",
    practice: "Double Bay Example Practice",
    reach: "Telehealth and practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-29",
    focus: "Trauma-aware assessment, emotional regulation",
    matchLine: "Says she takes assessment at a trauma-aware pace, with unhurried appointments and telehealth available from the first visit.",
    fitSignals: ["ADHD assessment", "Trauma-aware care", "Emotional regulation", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary:
      "Chloe says she takes assessment at a trauma-aware pace, keeps appointments unhurried, and offers the first appointment by telehealth for people who find rooms hard.",
    about:
      `Chloe is an invented example GP. Her profile declares trauma-aware ADHD assessment, emotional-regulation work, and telehealth-first appointments. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Trauma-aware general practice", "Emotional regulation and rejection sensitivity"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "trauma-informed", "emotional-regulation"],
    manner: ["attuned", "unhurried"],
    wheelchairAccessible: true,
    appointmentLength: "Extended first appointment",
    telehealthFirstAppointment: true,
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-minh-tran",
    name: "Dr Minh Tran",
    shortName: "Dr Tran",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Bondi Junction",
    practice: "Bondi Junction Example Clinic",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-21",
    focus: "ADHD assessment alongside anxiety, titration",
    matchLine: "Says he often works out anxiety from ADHD when they present through each other, with titration reviewed on a schedule.",
    fitSignals: ["ADHD assessment", "Anxiety", "Titration", "Vietnamese"],
    practicalSignals: ["Mixed billing", "Structured review schedule"],
    summary:
      "Minh says he often works out anxiety from ADHD when they present through each other, and reviews titration on a schedule rather than when something goes wrong. He consults in English and Vietnamese.",
    about:
      `Minh is an invented example GP. His profile declares frequent anxiety-and-ADHD work, scheduled titration review, and consultations in English and Vietnamese. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Anxiety care in general practice", "Titration and scheduled review"],
    languages: ["English", "Vietnamese"],
    careAreas: ["adhd-assessment", "anxiety", "titration"],
    manner: ["steadying", "structured"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment, scheduled reviews",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-isla-mcgregor",
    name: "Dr Isla McGregor",
    shortName: "Dr McGregor",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Hornsby",
    practice: "Hornsby Example Clinic",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    // Stale on purpose — the fourth stale-open declaration.
    capacityDeclaredAt: "2026-04-20",
    focus: "Complex presentations, shared care",
    matchLine: "Says she often holds complex presentations with their psychiatrist and carries the GP half of shared care.",
    fitSignals: ["ADHD assessment", "Complex presentations", "Shared care"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Isla says she often holds bipolar and other complex presentations together with their psychiatrist, and carries the GP half of shared-care plans.",
    about:
      `Isla is an invented example GP. Her profile declares frequent complex presentations held with their psychiatrist and shared-care arrangements. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Complex presentations held with their psychiatrist and team", "GP shared care under psychiatrist plans"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "complex-mental-health", "shared-care"],
    manner: ["sense_making", "steadying"],
    wheelchairAccessible: true,
    appointmentLength: "Appointment lengths set with the practice",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-jordan-reyes",
    name: "Dr Jordan Reyes",
    shortName: "Dr Reyes",
    gender: "non-binary",
    pronouns: "they/them",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Broadbeach",
    practice: "Broadbeach Example Clinic",
    reach: "Telehealth and practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-27",
    focus: "Emotional regulation, non-medication supports",
    matchLine: "Says emotional regulation is often the first thing they hear, decides the plan with the patient, and gives non-medication supports real room.",
    fitSignals: ["ADHD assessment", "Emotional regulation", "Non-medication supports", "Spanish", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary:
      "Jordan says emotional regulation and rejection sensitivity are often the first thing they hear, that the plan is decided with the patient, and that non-medication supports get real room. They consult in English and Spanish, with telehealth from the first appointment.",
    about:
      `Jordan is an invented example GP. Their profile declares frequent emotional-regulation work, non-medication supports, collaborative planning, telehealth-first appointments, and consultations in English and Spanish. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Emotional regulation and rejection sensitivity", "Non-medication and psychological supports"],
    languages: ["English", "Spanish"],
    careAreas: ["adhd-assessment", "emotional-regulation", "non-medication"],
    manner: ["collaborative", "non_judgmental"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment",
    telehealthFirstAppointment: true,
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-amara-obi",
    name: "Dr Amara Obi",
    shortName: "Dr Obi",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP DCH",
    suburb: "Southport",
    practice: "Southport Example Clinic",
    reach: "Practice appointments",
    image: null,
    // The fourth closed-books entry.
    acceptingNewPatients: false,
    capacityDeclaredAt: "2026-08-18",
    focus: "ADHD assessment in children and adults, low mood",
    matchLine: "Says she assesses across ages, often sees low mood alongside, and works from strengths.",
    fitSignals: ["ADHD assessment", "Children and adolescents", "Low mood", "Igbo"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Amara says she assesses ADHD across ages, often sees low mood alongside it, and works from strengths so people leave with a plan they can act on. She consults in English and Igbo.",
    about:
      `Amara is an invented example GP. Her profile declares ADHD assessment across ages, frequent depression care, and consultations in English and Igbo. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Child and adolescent assessment", "Depression care in general practice"],
    languages: ["English", "Igbo"],
    careAreas: ["adhd-assessment", "child-adolescent-adhd", "depression"],
    manner: ["motivating", "culturally_attuned"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-felix-braun",
    name: "Dr Felix Braun",
    shortName: "Dr Braun",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Epping",
    practice: "Epping Example Clinic",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-23",
    focus: "Co-occurring autism and ADHD, complex presentations",
    matchLine: "Says he often sees autism and ADHD presenting together, and holds complex presentations with their psychiatrist.",
    fitSignals: ["ADHD assessment", "Autism and ADHD", "Complex presentations"],
    practicalSignals: ["Mixed billing", "Structured review schedule"],
    summary:
      "Felix says he often sees co-occurring autism and ADHD, works to a documented plan, and holds complex presentations together with their psychiatrist.",
    about:
      `Felix is an invented example GP. His profile declares frequent co-occurring autism and ADHD work and complex presentations held with their psychiatrist. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Co-occurring autism and ADHD", "Complex presentations held with their psychiatrist and team"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "autism-adhd", "complex-mental-health"],
    manner: ["structured", "sense_making"],
    wheelchairAccessible: false,
    appointmentLength: "Long first appointment, scheduled reviews",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-sana-qureshi",
    name: "Dr Sana Qureshi",
    shortName: "Dr Qureshi",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Pennant Hills",
    practice: "Pennant Hills Example Clinic",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-26",
    focus: "ADHD assessment, titration, anxiety",
    matchLine: "Says she keeps first appointments unhurried, reviews titration on a schedule, and often sees anxiety alongside.",
    fitSignals: ["ADHD assessment", "Titration", "Anxiety", "Urdu & Hindi"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Sana says she keeps first appointments unhurried, reviews titration on a schedule, and often sees anxiety arrive with the ADHD question. She consults in English, Urdu and Hindi, and values culturally sensitive care.",
    about:
      `Sana is an invented example GP. Her profile declares frequent ADHD assessment, scheduled titration review, anxiety care, and consultations in English, Urdu and Hindi. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Titration and scheduled review", "Anxiety care in general practice"],
    languages: ["English", "Urdu", "Hindi"],
    careAreas: ["adhd-assessment", "titration", "anxiety"],
    manner: ["unhurried", "culturally_attuned"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
  {
    id: "example-ewan-blake",
    name: "Dr Ewan Blake",
    shortName: "Dr Blake",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Robina",
    practice: "Robina Example Clinic",
    reach: "Practice appointments",
    image: null,
    acceptingNewPatients: true,
    // Stale on purpose — the oldest declaration in the set, so the grade's far edge renders.
    capacityDeclaredAt: "2026-03-30",
    focus: "Structured assessment, substance history, shared care",
    matchLine: "Says he works from a documented baseline, takes a substance history as a safety question, and carries shared care when a psychiatrist holds the plan.",
    fitSignals: ["ADHD assessment", "Substance history", "Shared care"],
    practicalSignals: ["Mixed billing", "Structured review schedule"],
    summary:
      "Ewan says he works from a documented baseline, takes a substance history as a safety question rather than a judgement, and carries the GP half of shared care when a psychiatrist holds the plan.",
    about:
      `Ewan is an invented example GP. His profile declares structured assessment, substance-history care, and shared-care arrangements. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Structured adult ADHD assessment", "Substance-history care in general practice", "GP shared care under psychiatrist plans"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "substance-history", "shared-care"],
    manner: ["steadying", "non_judgmental"],
    wheelchairAccessible: true,
    appointmentLength: "Long first appointment, scheduled reviews",
    booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
    synthetic: true,
  },
];

/**
 * The roster the finder ranks while the tickbox is ON: the real entries first in source order,
 * then the personas. Source order is NOT display order — `rankClinicians` sorts it — this is
 * just the honest construction: nothing here removes or reorders a real entry.
 */
export const demoRoster: readonly Clinician[] = [...clinicians, ...SYNTHETIC_CLINICIANS];
