// O217: the synthetic example roster — invented GP profiles the finder can OPT INTO for testing.
//
// FOUNDER DECISION `synthetic-roster-tickbox` (src/design/founder-gates.ts, 2026-09-01) is the
// authority for this file's existence: the persona purge made the `clinicians` roster
// real-people-only, and the founder has asked for example profiles back — in the live finder,
// behind a reader-visible tickbox, this deployment only, because "this finder system of the
// adhdme repo is not public so it's ok it's just for testing".
//
// WHAT KEEPS THIS FROM BEING THE THING THE PURGE REMOVED. The purge's harm was invented detail
// PRESENTED AS REAL: fabricated availability under plausible names, bookable-looking mocks.
// Every line of defence here is against that, and `synthetic-roster.test.ts` enforces each:
//   * `synthetic: true` on every entry, never `realPerson` — the surfaces read the flag and say
//     "Example profile" out loud wherever one renders;
//   * `image` is a CREDITED STOCK PORTRAIT or null — never a generated face. O242 (founder-directed)
//     gave the personas photographs from Unsplash and Pexels, self-hosted and credited by name in
//     `portrait-credits.ts`; a generated face would still be a fabricated person presented as
//     genuine, and the register's test refuses any image that is not in it;
//   * `booking.via: "synthetic-none"` with no url — there is nobody to book and no control that
//     pretends otherwise;
//   * practice names self-mark ("… Example Practice" / "… Example Clinic"), so no invented name can collide with
//     a real business;
//   * no `disclosedInterest` — an invented conflict is still an invented claim, and the
//     founder-behind ranking laws stay testable against real data only;
//   * every rendered string passes the same patient-surface linter as real copy — invented does
//     not mean exempt, it renders to the same reader;
//   * the `clinicians` export, ROSTER_SIZE, the coverage map and every public count stay
//     real-only: this list reaches a ranking ONLY through the finder's tickbox.
//
// THIS IS NOT `syntheticClinician()` (synthetic-clinician.ts) AND MUST NOT MERGE WITH IT. That
// template is the engine tests' neutral blank and its own law says it never reaches a surface;
// these personas exist to reach one. Coupling them would put fifty ranking laws back at the
// mercy of somebody editing a persona for looks — the exact tangle W193/O179 untied.
//
// WHY THE SET LOOKS THE WAY IT DOES. Twenty personas (founder follow-up, same day: "Let's put
// in 20 synthetic profiles"), designed rather than sampled: together with the two real GPs they
// cover every `CareArea` in the closed vocabulary AND every language in `MATCHABLE_LANGUAGES`,
// all three genders, every manner facet, four closed books (the closed-outranks-nothing law
// visible in more than one suburb), stale and fresh capacity declarations (all three O56
// freshness grades render), and four telehealth-first entries (the distance law's exception
// exercised). Suburbs are real gazetteer rows so computed distance works — a suburb is a
// place, not a person, and inventing one would break the arithmetic without protecting
// anybody.

import type { Clinician } from "./roster";
import { portraitFor } from "./portrait-credits";
import { clinicians } from "./roster";

/** The one sentence every persona's `about` must end with — the census pins its presence. */
export const SYNTHETIC_ABOUT_NOTICE =
  "This is a fictional example profile used for trying the finder. It describes nobody.";

/** The shared booking explanation — the census pins that no persona carries anything else. */
/**
 * O231 (founder-directed, amending `synthetic-roster-tickbox`): the booking route, in the product's
 * own voice.
 *
 * It USED to read "This is an example profile used for trying the finder. There is nobody to book."
 * and it stood WHERE THE BUTTON GOES, so the journey dead-ended one tap from the end — the largest
 * single reason the app did not read as finished, found by the O231 screenshot sweep.
 *
 * WHAT DID NOT CHANGE, AND THIS IS THE LINE THE UNIT HOLDS: there is still no `url`, so `/go/` has
 * nothing to read and no control anywhere opens a fabricated booking listing. The variant is still
 * `synthetic-none` in the type. An invented PHONE NUMBER, an external listing or a "request sent"
 * confirmation that sends nothing would not be sample data, and none of the three is here.
 *
 * 2026-09-05, from the finder re-walk: the note used to read "Appointments with this practice are
 * arranged by phone." — a sentence that describes a route and then gives no number, so a first-time
 * reader on the booking screen looked for a phone number that never came. The screen was a designed
 * terminal state that did not say so. It says so now: an example, nobody to ring, and the two ways
 * onward (the list, or the switch that hides examples). `synthetic-booking.test.ts` holds it.
 */
export const SYNTHETIC_BOOKING_NOTE =
  "This is an example profile, so there is no practice to ring and nothing to book here. Go back to the list to choose a listed GP, or turn example profiles off in Settings.";

/**
 * O222: the four defences every persona repeats verbatim, made structural. `image`, `booking`
 * and `synthetic` are not per-persona facts — they are the LAW of this file, and 20 hand-copies
 * of a law are 20 places a hand-edit can silently break it. `reach` is derived from the one
 * field it always correlated with. Everything DISTINGUISHING — name, suburb, care areas, the
 * copy a reader meets — stays a literal on the entry, because those are what a reviewer reads.
 */
const example = (p: Omit<Clinician, "image" | "booking" | "synthetic" | "reach">): Clinician => ({
  ...p,
  // O242: a credited stock portrait, or null by the register's own list — never a generated face.
  image: portraitFor(p.id),
  reach: p.telehealthFirstAppointment ? "Telehealth and practice appointments" : "Practice appointments",
  booking: { via: "synthetic-none", note: SYNTHETIC_BOOKING_NOTE },
  synthetic: true,
});

export const SYNTHETIC_CLINICIANS: readonly Clinician[] = [
  example({
    id: "example-mei-chao",
    name: "Dr Mei Chao",
    shortName: "Dr Chao",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Epping",
    practice: "Epping Example Practice",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-25",
    focus: "ADHD assessment across ages, titration",
    matchLine: "Says she sees ADHD assessment often, for adults and for school-age patients, with titration reviewed on a schedule.",
    fitSignals: ["ADHD assessment", "Children and adolescents", "Titration", "Mandarin"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Mei says she sees ADHD assessment often, in adults and in children and adolescents, and reviews titration on a set schedule. She consults in English and Mandarin.",
    about:
      `Mei is an invented example GP. Her profile declares frequent adult and child ADHD assessment, scheduled titration review, and consultations in English and Mandarin. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Structured adult ADHD assessment", "Child and adolescent assessment", "Titration and scheduled review"],
    languages: ["English", "Mandarin"],
    careAreas: ["adhd-assessment", "child-adolescent-adhd", "titration"],
    manner: ["unhurried", "collaborative"],
    wheelchairAccessible: true,
    consultRecording: "ai-scribe",
    approach: ["holistic"],
    appointmentLength: "Long first appointment",
  }),
  example({
    id: "example-tomas-rivera",
    name: "Dr Tomás Rivera",
    shortName: "Dr Rivera",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MD FRACGP",
    suburb: "Bondi Junction",
    practice: "Bondi Junction Example Practice",
    acceptingNewPatients: true,
    // Stale on purpose: an open declaration past the 90-day freshness window, so the
    // stale-open capacity grade renders somewhere a tester can see it.
    capacityDeclaredAt: "2026-04-02",
    focus: "ADHD assessment alongside low mood and anxiety",
    matchLine: "Says he often sees ADHD questions that arrive together with low mood or anxiety.",
    fitSignals: ["ADHD assessment", "Low mood", "Anxiety", "Spanish"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Tomás says he often sees ADHD questions that arrive together with low mood or anxiety, and works out with the patient which thread to pull first. He consults in English and Spanish.",
    about:
      `Tomás is an invented example GP. His profile declares frequent ADHD assessment alongside depression and anxiety care, and consultations in English and Spanish. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Depression and anxiety care in general practice"],
    languages: ["English", "Spanish"],
    careAreas: ["adhd-assessment", "depression", "anxiety"],
    manner: ["attuned", "non_judgmental"],
    wheelchairAccessible: true,
    consultRecording: "no-ai",
    approach: ["functional"],
    appointmentLength: "Appointment lengths set with the practice",
  }),
  example({
    id: "example-priya-nair",
    name: "Dr Priya Nair",
    shortName: "Dr Nair",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP DCH",
    suburb: "Hornsby",
    practice: "Hornsby Example Practice",
    // Closed books: the closed-never-outranks-open-at-equal-fit law, visible to a tester.
    // O251: six personas moved from Sydney to the Gold Coast (Burleigh Heads, Coolangatta,
    // Helensvale, Nerang, Varsity Lakes, Palm Beach) so a room of Gold Coast GPs sees the coast
    // populated; twenty stays twenty (G-SYN-3), portraits and declarations unchanged.
    acceptingNewPatients: false,
    capacityDeclaredAt: "2026-08-20",
    focus: "ADHD and autism presenting together, non-medication supports",
    matchLine: "Says she often sees ADHD and autism presenting together, and gives the non-medication half of a plan real room.",
    fitSignals: ["ADHD assessment", "Autism and ADHD", "Non-medication supports", "Malayalam"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Priya says she often sees co-occurring ADHD and autism, and puts as much of the plan into non-medication supports as into anything else. She consults in English and Malayalam.",
    about:
      `Priya is an invented example GP. Her profile declares frequent co-occurring ADHD and autism work and non-medication supports, and consultations in English and Malayalam. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Co-occurring autism and ADHD", "Non-medication and psychological supports"],
    languages: ["English", "Malayalam"],
    careAreas: ["adhd-assessment", "autism-adhd", "non-medication"],
    manner: ["sense_making", "collaborative"],
    wheelchairAccessible: false,
    consultRecording: "ai-scribe",
    approach: ["wearables"],
    appointmentLength: "Long first appointment",
  }),
  example({
    id: "example-owen-hartley",
    name: "Dr Owen Hartley",
    shortName: "Dr Hartley",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Southport",
    practice: "Southport Example Practice",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-28",
    focus: "Structured assessment, titration, substance history taken seriously",
    matchLine: "Says he works from a documented baseline, reviews titration on a schedule, and takes a substance history as a safety question.",
    fitSignals: ["ADHD assessment", "Titration", "Substance history", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary:
      "Owen says he works from a documented baseline, reviews titration on a schedule, and takes a substance history as a safety question rather than a judgement. First appointments can be by telehealth.",
    about:
      `Owen is an invented example GP. His profile declares structured assessment, scheduled titration review, substance-history care, and telehealth-first appointments. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Structured adult ADHD assessment", "Titration and scheduled review", "Substance-history care in general practice"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "titration", "substance-history"],
    manner: ["structured", "steadying"],
    wheelchairAccessible: true,
    consultRecording: "no-ai",
    approach: ["holistic", "wearables"],
    appointmentLength: "Long first appointment, scheduled reviews",
    telehealthFirstAppointment: true,
  }),
  example({
    id: "example-sarah-whitfield",
    name: "Dr Sarah Whitfield",
    shortName: "Dr Whitfield",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Pennant Hills",
    practice: "Pennant Hills Example Practice",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-22",
    focus: "Trauma-aware assessment, emotional regulation",
    matchLine: "Says she often sees emotional regulation and rejection sensitivity first, and takes assessment at a trauma-aware pace.",
    fitSignals: ["ADHD assessment", "Emotional regulation", "Trauma-aware care"],
    practicalSignals: ["Mixed billing", "Extended first appointment"],
    summary:
      "Sarah says the thing she hears first is often emotional regulation and rejection sensitivity, and that she takes assessment at a trauma-aware pace with time to be heard.",
    about:
      `Sarah is an invented example GP. Her profile declares trauma-aware ADHD assessment and frequent emotional-regulation work. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Trauma-aware general practice", "Emotional regulation and rejection sensitivity"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "emotional-regulation", "trauma-informed"],
    manner: ["attuned", "steadying", "non_judgmental"],
    wheelchairAccessible: true,
    consultRecording: "ai-scribe",
    appointmentLength: "Extended first appointment",
  }),
  example({
    id: "example-daniel-okafor",
    name: "Dr Daniel Okafor",
    shortName: "Dr Okafor",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Surfers Paradise",
    practice: "Surfers Paradise Example Practice",
    acceptingNewPatients: true,
    // Stale on purpose — the second stale-open grade, so the state is not a single row's quirk.
    capacityDeclaredAt: "2026-03-15",
    focus: "Shared care, complex presentations held with their psychiatrist",
    matchLine: "Says he often carries GP shared care under a psychiatrist's plan, including complex presentations.",
    fitSignals: ["ADHD assessment", "Shared care", "Complex presentations", "Igbo"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Daniel says he often carries GP shared care under a psychiatrist's or paediatrician's plan, including bipolar and other complex presentations held with their psychiatrist and team. He consults in English and Igbo.",
    about:
      `Daniel is an invented example GP. His profile declares frequent shared-care arrangements and complex presentations held with their psychiatrist, and consultations in English and Igbo. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["GP shared care under psychiatrist plans", "Complex presentations held with their psychiatrist and team"],
    languages: ["English", "Igbo"],
    careAreas: ["adhd-assessment", "shared-care", "complex-mental-health"],
    manner: ["sense_making", "structured"],
    wheelchairAccessible: true,
    consultRecording: "no-ai",
    approach: ["functional", "wearables"],
    appointmentLength: "Appointment lengths set with the practice",
  }),
  example({
    id: "example-hana-yoshida",
    name: "Dr Hana Yoshida",
    shortName: "Dr Yoshida",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Burleigh Heads",
    practice: "Burleigh Heads Example Practice",
    // The second closed-books entry, so closed rows appear in more than one suburb.
    acceptingNewPatients: false,
    capacityDeclaredAt: "2026-08-10",
    focus: "ADHD assessment alongside anxiety, non-medication supports",
    matchLine: "Says she often sees anxiety and ADHD presenting through each other, with unhurried appointments and non-medication supports in the plan.",
    fitSignals: ["ADHD assessment", "Anxiety", "Non-medication supports", "Vietnamese"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Hana says she often sees anxiety and ADHD presenting through each other, keeps first appointments unhurried, and gives non-medication supports real room in the plan. She consults in English and Vietnamese.",
    about:
      `Hana is an invented example GP. Her profile declares frequent anxiety-and-ADHD work, unhurried appointments and non-medication supports, and consultations in English and Vietnamese. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Anxiety care in general practice", "Non-medication and psychological supports"],
    languages: ["English", "Vietnamese"],
    careAreas: ["adhd-assessment", "anxiety", "non-medication"],
    careAreasSometimes: ["depression"],
    manner: ["unhurried", "culturally_attuned"],
    wheelchairAccessible: false,
    consultRecording: "ai-scribe",
    approach: ["holistic"],
    appointmentLength: "Long first appointment",
  }),
  example({
    id: "example-ash-coleman",
    name: "Dr Ash Coleman",
    shortName: "Dr Coleman",
    gender: "non-binary",
    pronouns: "they/them",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Robina",
    practice: "Robina Example Practice",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-27",
    focus: "ADHD assessment, low mood, emotional regulation",
    matchLine: "Says they often see ADHD alongside low mood and emotional regulation, and decide the plan with the patient.",
    fitSignals: ["ADHD assessment", "Low mood", "Emotional regulation", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary:
      "Ash says they often see ADHD alongside low mood and emotional-regulation questions, work from strengths, and decide the plan with the patient rather than for them. First appointments can be by telehealth.",
    about:
      `Ash is an invented example GP. Their profile declares frequent ADHD, low-mood and emotional-regulation work, collaborative planning, and telehealth-first appointments. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Depression care in general practice", "Emotional regulation and rejection sensitivity"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "depression", "emotional-regulation"],
    manner: ["collaborative", "motivating"],
    wheelchairAccessible: true,
    consultRecording: "no-ai",
    appointmentLength: "Long first appointment",
    telehealthFirstAppointment: true,
  }),
  example({
    id: "example-leila-haddad",
    name: "Dr Leila Haddad",
    shortName: "Dr Haddad",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Coolangatta",
    practice: "Coolangatta Example Practice",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-26",
    focus: "ADHD assessment alongside anxiety, emotional regulation",
    matchLine: "Says she often sees anxiety and emotional-regulation questions arrive first, and keeps the room settled while the assessment takes its course.",
    fitSignals: ["ADHD assessment", "Anxiety", "Emotional regulation", "Arabic"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Leila says anxiety and emotional-regulation questions are often what she hears first, and that she keeps the room settled while an assessment takes its course. She consults in English and Arabic.",
    about:
      `Leila is an invented example GP. Her profile declares frequent anxiety and emotional-regulation work alongside ADHD assessment, and consultations in English and Arabic. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Anxiety care in general practice", "Emotional regulation and rejection sensitivity"],
    languages: ["English", "Arabic"],
    careAreas: ["adhd-assessment", "anxiety", "emotional-regulation"],
    manner: ["attuned", "steadying"],
    wheelchairAccessible: true,
    consultRecording: "ai-scribe",
    approach: ["holistic", "functional", "wearables"],
    appointmentLength: "Long first appointment",
  }),
  example({
    id: "example-gurpreet-singh",
    name: "Dr Gurpreet Singh",
    shortName: "Dr Singh",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Helensvale",
    practice: "Helensvale Example Practice",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-24",
    focus: "Structured assessment, titration, shared care",
    matchLine: "Says he works to a documented plan, reviews titration at set intervals, and often carries shared care under a psychiatrist's plan.",
    fitSignals: ["ADHD assessment", "Titration", "Shared care", "Punjabi"],
    practicalSignals: ["Mixed billing", "Structured review schedule"],
    summary:
      "Gurpreet says he works to a documented plan, reviews titration at set intervals, and often carries GP shared care under a psychiatrist's plan. He consults in English and Punjabi.",
    about:
      `Gurpreet is an invented example GP. His profile declares structured assessment, scheduled titration review, shared-care arrangements, and consultations in English and Punjabi. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Structured adult ADHD assessment", "Titration and scheduled review", "GP shared care under psychiatrist plans"],
    languages: ["English", "Punjabi"],
    careAreas: ["adhd-assessment", "titration", "shared-care"],
    manner: ["structured", "collaborative"],
    wheelchairAccessible: true,
    consultRecording: "no-ai",
    approach: ["wearables"],
    appointmentLength: "Long first appointment, scheduled reviews",
  }),
  example({
    id: "example-annika-larsen",
    name: "Dr Annika Larsen",
    shortName: "Dr Larsen",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP DCH",
    suburb: "Broadbeach",
    practice: "Broadbeach Example Practice",
    // The third closed-books entry — closed rows on the Gold Coast side of the map too.
    acceptingNewPatients: false,
    capacityDeclaredAt: "2026-08-15",
    focus: "ADHD assessment in children and adolescents, non-medication supports",
    matchLine: "Says she often assesses school-age patients, with the non-medication half of the plan given real room.",
    fitSignals: ["ADHD assessment", "Children and adolescents", "Non-medication supports"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Annika says much of her ADHD work is with children and adolescents, run through school as well as home, and that non-medication supports get as much of the plan as anything else.",
    about:
      `Annika is an invented example GP. Her profile declares frequent child and adolescent ADHD assessment and non-medication supports. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Child and adolescent ADHD assessment", "Non-medication and psychological supports"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "child-adolescent-adhd", "non-medication"],
    manner: ["unhurried", "motivating"],
    wheelchairAccessible: true,
    consultRecording: "ai-scribe",
    approach: ["holistic"],
    appointmentLength: "Extended first appointment",
  }),
  example({
    id: "example-rohan-pillai",
    name: "Dr Rohan Pillai",
    shortName: "Dr Pillai",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Beecroft",
    practice: "Beecroft Example Practice",
    acceptingNewPatients: true,
    // Stale on purpose — a third stale-open declaration, in a suburb a real GP also consults.
    capacityDeclaredAt: "2026-05-10",
    focus: "ADHD assessment alongside low mood, substance history taken seriously",
    matchLine: "Says he often sees low mood arrive with an ADHD question, and takes a substance history as a safety question rather than a judgement.",
    fitSignals: ["ADHD assessment", "Low mood", "Substance history", "Tamil"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Rohan says low mood often arrives with the ADHD question, and that he takes a substance history as a safety question rather than a judgement. He consults in English and Tamil.",
    about:
      `Rohan is an invented example GP. His profile declares frequent ADHD-and-depression work, substance-history care, and consultations in English and Tamil. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Depression care in general practice", "Substance-history care in general practice"],
    languages: ["English", "Tamil"],
    careAreas: ["adhd-assessment", "depression", "substance-history"],
    manner: ["non_judgmental", "sense_making"],
    wheelchairAccessible: false,
    consultRecording: "no-ai",
    approach: ["functional"],
    appointmentLength: "Appointment lengths set with the practice",
  }),
  example({
    id: "example-chloe-bennett",
    name: "Dr Chloe Bennett",
    shortName: "Dr Bennett",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Double Bay",
    practice: "Double Bay Example Practice",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-29",
    focus: "Trauma-aware assessment, emotional regulation",
    matchLine: "Says she takes assessment at a trauma-aware pace, with unhurried appointments and telehealth available from the first visit.",
    fitSignals: ["ADHD assessment", "Trauma-aware care", "Emotional regulation", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary:
      "Chloe says she takes assessment at a trauma-aware pace, keeps appointments unhurried, and offers the first appointment by telehealth for people who find rooms hard.",
    about:
      `Chloe is an invented example GP. Her profile declares trauma-aware ADHD assessment, emotional-regulation work, and telehealth-first appointments. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Trauma-aware general practice", "Emotional regulation and rejection sensitivity"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "trauma-informed", "emotional-regulation"],
    manner: ["attuned", "unhurried"],
    wheelchairAccessible: true,
    consultRecording: "ai-scribe",
    approach: ["wearables"],
    appointmentLength: "Extended first appointment",
    telehealthFirstAppointment: true,
  }),
  example({
    id: "example-minh-tran",
    name: "Dr Minh Tran",
    shortName: "Dr Tran",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Nerang",
    practice: "Nerang Example Clinic",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-21",
    focus: "ADHD assessment alongside anxiety, titration",
    matchLine: "Says he often works out anxiety from ADHD when they present through each other, with titration reviewed on a schedule.",
    fitSignals: ["ADHD assessment", "Anxiety", "Titration", "Vietnamese"],
    practicalSignals: ["Mixed billing", "Structured review schedule"],
    summary:
      "Minh says he often works out anxiety from ADHD when they present through each other, and reviews titration on a schedule rather than when something goes wrong. He consults in English and Vietnamese.",
    about:
      `Minh is an invented example GP. His profile declares frequent anxiety-and-ADHD work, scheduled titration review, and consultations in English and Vietnamese. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Anxiety care in general practice", "Titration and scheduled review"],
    languages: ["English", "Vietnamese"],
    careAreas: ["adhd-assessment", "anxiety", "titration"],
    manner: ["steadying", "structured"],
    wheelchairAccessible: true,
    consultRecording: "no-ai",
    approach: ["holistic", "wearables"],
    appointmentLength: "Long first appointment, scheduled reviews",
  }),
  example({
    id: "example-isla-mcgregor",
    name: "Dr Isla McGregor",
    shortName: "Dr McGregor",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Varsity Lakes",
    practice: "Varsity Lakes Example Clinic",
    acceptingNewPatients: true,
    // Stale on purpose — the fourth stale-open declaration.
    capacityDeclaredAt: "2026-04-20",
    focus: "Complex presentations, shared care",
    matchLine: "Says she often holds complex presentations with their psychiatrist and carries the GP half of shared care.",
    fitSignals: ["ADHD assessment", "Complex presentations", "Shared care"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Isla says she often holds bipolar and other complex presentations together with their psychiatrist, and carries the GP half of shared-care plans.",
    about:
      `Isla is an invented example GP. Her profile declares frequent complex presentations held with their psychiatrist and shared-care arrangements. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Complex presentations held with their psychiatrist and team", "GP shared care under psychiatrist plans"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "complex-mental-health", "shared-care"],
    manner: ["sense_making", "steadying"],
    wheelchairAccessible: true,
    consultRecording: "ai-scribe",
    appointmentLength: "Appointment lengths set with the practice",
  }),
  example({
    id: "example-jordan-reyes",
    name: "Dr Jordan Reyes",
    shortName: "Dr Reyes",
    gender: "non-binary",
    pronouns: "they/them",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Broadbeach",
    practice: "Broadbeach Example Clinic",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-27",
    focus: "Emotional regulation, non-medication supports",
    matchLine: "Says emotional regulation is often the first thing they hear, decides the plan with the patient, and gives non-medication supports real room.",
    fitSignals: ["ADHD assessment", "Emotional regulation", "Non-medication supports", "Spanish", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary:
      "Jordan says emotional regulation and rejection sensitivity are often the first thing they hear, that the plan is decided with the patient, and that non-medication supports get real room. They consult in English and Spanish, with telehealth from the first appointment.",
    about:
      `Jordan is an invented example GP. Their profile declares frequent emotional-regulation work, non-medication supports, collaborative planning, telehealth-first appointments, and consultations in English and Spanish. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Emotional regulation and rejection sensitivity", "Non-medication and psychological supports"],
    languages: ["English", "Spanish"],
    careAreas: ["adhd-assessment", "emotional-regulation", "non-medication"],
    manner: ["collaborative", "non_judgmental"],
    wheelchairAccessible: true,
    consultRecording: "no-ai",
    approach: ["functional", "wearables"],
    appointmentLength: "Long first appointment",
    telehealthFirstAppointment: true,
  }),
  example({
    id: "example-amara-obi",
    name: "Dr Amara Obi",
    shortName: "Dr Obi",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP DCH",
    suburb: "Southport",
    practice: "Southport Example Clinic",
    // The fourth closed-books entry.
    acceptingNewPatients: false,
    capacityDeclaredAt: "2026-08-18",
    focus: "ADHD assessment in children and adults, low mood",
    matchLine: "Says she assesses across ages, often sees low mood alongside, and works from strengths.",
    fitSignals: ["ADHD assessment", "Children and adolescents", "Low mood", "Igbo"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Amara says she assesses ADHD across ages, often sees low mood alongside it, and works from strengths so people leave with a plan they can act on. She consults in English and Igbo.",
    about:
      `Amara is an invented example GP. Her profile declares ADHD assessment across ages, frequent depression care, and consultations in English and Igbo. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Child and adolescent assessment", "Depression care in general practice"],
    languages: ["English", "Igbo"],
    careAreas: ["adhd-assessment", "child-adolescent-adhd", "depression"],
    manner: ["motivating", "culturally_attuned"],
    wheelchairAccessible: true,
    consultRecording: "ai-scribe",
    approach: ["holistic"],
    appointmentLength: "Long first appointment",
  }),
  example({
    id: "example-felix-braun",
    name: "Dr Felix Braun",
    shortName: "Dr Braun",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Palm Beach",
    practice: "Palm Beach Example Clinic",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-23",
    focus: "Co-occurring autism and ADHD, complex presentations",
    matchLine: "Says he often sees autism and ADHD presenting together, and holds complex presentations with their psychiatrist.",
    fitSignals: ["ADHD assessment", "Autism and ADHD", "Complex presentations"],
    practicalSignals: ["Mixed billing", "Structured review schedule"],
    summary:
      "Felix says he often sees co-occurring autism and ADHD, works to a documented plan, and holds complex presentations together with their psychiatrist.",
    about:
      `Felix is an invented example GP. His profile declares frequent co-occurring autism and ADHD work and complex presentations held with their psychiatrist. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Co-occurring autism and ADHD", "Complex presentations held with their psychiatrist and team"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "autism-adhd", "complex-mental-health"],
    manner: ["structured", "sense_making"],
    wheelchairAccessible: false,
    consultRecording: "no-ai",
    appointmentLength: "Long first appointment, scheduled reviews",
  }),
  example({
    id: "example-sana-qureshi",
    name: "Dr Sana Qureshi",
    shortName: "Dr Qureshi",
    gender: "woman",
    pronouns: "she/her",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Pennant Hills",
    practice: "Pennant Hills Example Clinic",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-26",
    focus: "ADHD assessment, titration, anxiety",
    matchLine: "Says she keeps first appointments unhurried, reviews titration on a schedule, and often sees anxiety alongside.",
    fitSignals: ["ADHD assessment", "Titration", "Anxiety", "Urdu & Hindi"],
    practicalSignals: ["Mixed billing"],
    summary:
      "Sana says she keeps first appointments unhurried, reviews titration on a schedule, and often sees anxiety arrive with the ADHD question. She consults in English, Urdu and Hindi, and values culturally sensitive care.",
    about:
      `Sana is an invented example GP. Her profile declares frequent ADHD assessment, scheduled titration review, anxiety care, and consultations in English, Urdu and Hindi. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD assessment", "Titration and scheduled review", "Anxiety care in general practice"],
    languages: ["English", "Urdu", "Hindi"],
    careAreas: ["adhd-assessment", "titration", "anxiety"],
    manner: ["unhurried", "culturally_attuned"],
    wheelchairAccessible: true,
    consultRecording: "ai-scribe",
    approach: ["holistic", "functional", "wearables"],
    appointmentLength: "Long first appointment",
  }),
  example({
    id: "example-ewan-blake",
    name: "Dr Ewan Blake",
    shortName: "Dr Blake",
    gender: "man",
    pronouns: "he/him",
    title: "General practitioner, MBBS FRACGP",
    suburb: "Robina",
    practice: "Robina Example Clinic",
    acceptingNewPatients: true,
    // Stale on purpose — the oldest declaration in the set, so the grade's far edge renders.
    capacityDeclaredAt: "2026-03-30",
    focus: "Structured assessment, substance history, shared care",
    matchLine: "Says he works from a documented baseline, takes a substance history as a safety question, and carries shared care when a psychiatrist holds the plan.",
    fitSignals: ["ADHD assessment", "Substance history", "Shared care"],
    practicalSignals: ["Mixed billing", "Structured review schedule"],
    summary:
      "Ewan says he works from a documented baseline, takes a substance history as a safety question rather than a judgement, and carries the GP half of shared care when a psychiatrist holds the plan.",
    about:
      `Ewan is an invented example GP. His profile declares structured assessment, substance-history care, and shared-care arrangements. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Structured adult ADHD assessment", "Substance-history care in general practice", "GP shared care under psychiatrist plans"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "substance-history", "shared-care"],
    manner: ["steadying", "non_judgmental"],
    wheelchairAccessible: true,
    consultRecording: "no-ai",
    approach: ["wearables"],
    appointmentLength: "Long first appointment, scheduled reviews",
  }),
];


// ── 2026-09-08 (founder-directed, the ADHD Life PRD §38, §40–§41): the allied example providers ──
//
// "Make that finder page broaden out so it is not just GPs." The roster gains ten invented allied
// providers — two each of psychologist, counsellor, occupational therapist, exercise physiologist
// and ADHD coach — on exactly the terms the twenty example GPs hold: `synthetic: true`, no url,
// a self-marking practice name, a credited portrait or a monogram, and every string passing the
// patient linter. Each carries a `profession` and an `expertise` list from the closed taxonomy,
// which is what the support path and the match reasons read. Suburbs are gazetteer rows so the
// distance arithmetic works; they are spread across both focus areas on purpose.
//
// WHAT THEY DECLARE. `careAreas` stays the assessment-centred vocabulary the engine reads, so an
// allied provider declares the areas that are honestly theirs — non-medication supports, emotional
// regulation, anxiety, depression — and never `adhd-assessment`, which they do not do. A sentence
// asking for an assessment therefore still ranks the GPs first, which is the truth.

export const ALLIED_CLINICIANS: readonly Clinician[] = [
  example({
    id: "example-hannah-liu",
    name: "Hannah Liu",
    shortName: "Hannah",
    gender: "woman",
    pronouns: "she/her",
    title: "Psychologist, MPsych(Clin)",
    profession: "psychologist",
    expertise: ["emotional-regulation", "perfectionism", "late-diagnosis"],
    suburb: "Chatswood",
    practice: "Chatswood Example Psychology",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-30",
    focus: "Emotional regulation, perfectionism and late recognition of ADHD",
    matchLine: "Says she works with adults on the emotional side of ADHD, fast-arriving feelings, perfectionism, and what a late recognition stirs up.",
    fitSignals: ["Emotional regulation", "Perfectionism", "Late recognition", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary: "Hannah says she works with adults on emotional regulation and perfectionism alongside ADHD, and with the questions a late recognition raises. First appointments can be by telehealth.",
    about: `Hannah is an invented example psychologist. Her profile declares work on emotional regulation, perfectionism and late recognition, by telehealth or in rooms. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Emotional regulation in adults with ADHD", "Perfectionism and starting", "Late recognition"],
    languages: ["English", "Mandarin"],
    careAreas: ["emotional-regulation", "anxiety", "non-medication"],
    manner: ["attuned", "non_judgmental"],
    wheelchairAccessible: true,
    telehealthFirstAppointment: true,
    appointmentLength: "Fifty-minute sessions",
  }),
  example({
    id: "example-daniel-okafor",
    name: "Daniel Okafor",
    shortName: "Daniel",
    gender: "man",
    pronouns: "he/him",
    title: "Psychologist, MPsych",
    profession: "psychologist",
    expertise: ["adhd-couples", "emotional-regulation", "university-adhd"],
    suburb: "Burleigh Heads",
    practice: "Burleigh Example Psychology",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-27",
    focus: "Couples where one partner has ADHD, and university students",
    matchLine: "Says he sees couples where ADHD is in the room, and students whose course is not built for how they work.",
    fitSignals: ["ADHD in couples", "University ADHD", "Emotional regulation"],
    practicalSignals: ["Mixed billing"],
    summary: "Daniel says he works with couples where one partner has ADHD, and with university students on the emotional load of study. He consults in rooms on the Gold Coast.",
    about: `Daniel is an invented example psychologist. His profile declares work with couples and with university students. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Couples work where ADHD is part of the picture", "University students with ADHD"],
    languages: ["English"],
    careAreas: ["emotional-regulation", "depression", "non-medication"],
    manner: ["sense_making", "collaborative"],
    wheelchairAccessible: true,
    appointmentLength: "Fifty-minute sessions",
  }),
  example({
    id: "example-ruth-bennett",
    name: "Ruth Bennett",
    shortName: "Ruth",
    gender: "woman",
    pronouns: "she/her",
    title: "Counsellor, MCouns",
    profession: "counsellor",
    expertise: ["adhd-couples", "late-diagnosis"],
    suburb: "Hornsby",
    practice: "Hornsby Example Counselling",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-22",
    focus: "Relationships and the conversations that keep going wrong",
    matchLine: "Says she works with people and couples on the conversations that keep going the same way, being unheard, forgotten commitments, the fast escalation.",
    fitSignals: ["Relationships", "ADHD in couples", "Late recognition"],
    practicalSignals: ["Private fees", "Telehealth follow-ups"],
    summary: "Ruth says she works with individuals and couples on relationships where ADHD is part of the pattern, and on what a late recognition changes. In rooms or by telehealth.",
    about: `Ruth is an invented example counsellor. Her profile declares relationship and couples work and support around late recognition. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Couples counselling", "Late recognition of ADHD in adults"],
    languages: ["English"],
    careAreas: ["emotional-regulation", "non-medication"],
    manner: ["attuned", "unhurried"],
    wheelchairAccessible: false,
    telehealthFirstAppointment: true,
    appointmentLength: "Hour-long sessions",
  }),
  example({
    id: "example-marco-de-luca",
    name: "Marco De Luca",
    shortName: "Marco",
    gender: "man",
    pronouns: "he/him",
    title: "Counsellor, BCouns",
    profession: "counsellor",
    expertise: ["university-adhd", "late-diagnosis"],
    suburb: "Southport",
    practice: "Southport Example Counselling",
    acceptingNewPatients: false,
    capacityDeclaredAt: "2026-08-15",
    focus: "Young adults finding their feet, in study and in the first jobs",
    matchLine: "Says he works with people in their late teens and twenties on study, first jobs and living independently with ADHD.",
    fitSignals: ["University ADHD", "Early career", "Italian"],
    practicalSignals: ["Private fees"],
    summary: "Marco says he works with young adults on study, early career and independent life with ADHD. He consults in English and Italian; his books are currently closed.",
    about: `Marco is an invented example counsellor. His profile declares work with young adults on study and early working life. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Young adult counselling", "Study and early career"],
    languages: ["English", "Italian"],
    careAreas: ["emotional-regulation", "non-medication"],
    manner: ["motivating", "non_judgmental"],
    wheelchairAccessible: true,
    appointmentLength: "Hour-long sessions",
  }),
  example({
    id: "example-jane-whitlock",
    name: "Jane Whitlock",
    shortName: "Jane",
    gender: "woman",
    pronouns: "she/her",
    title: "Occupational therapist, BOccThy",
    profession: "occupational-therapist",
    expertise: ["adhd-work-systems", "task-initiation", "workplace-adjustments"],
    suburb: "Epping",
    practice: "Epping Example Occupational Therapy",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-09-01",
    focus: "Practical executive-function systems in real workplaces",
    matchLine: "Says she works with adults on starting ambiguous work, building systems that survive a real job, and the adjustments worth asking a workplace for.",
    fitSignals: ["ADHD at work", "Task initiation", "Workplace systems", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary: "Jane says she works with adults on practical executive-function systems at work, starting, organising, and the adjustments a workplace can make. Structured and goal-focused, in rooms or by telehealth.",
    about: `Jane is an invented example occupational therapist. Her profile declares work on task initiation, work systems and workplace adjustments. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Executive-function systems at work", "Task initiation", "Workplace adjustments"],
    languages: ["English"],
    careAreas: ["non-medication"],
    manner: ["structured", "collaborative"],
    wheelchairAccessible: true,
    telehealthFirstAppointment: true,
    appointmentLength: "Hour-long sessions",
  }),
  example({
    id: "example-sofia-martins",
    name: "Sofia Martins",
    shortName: "Sofia",
    gender: "woman",
    pronouns: "she/her",
    title: "Occupational therapist, MOccThy",
    profession: "occupational-therapist",
    expertise: ["household-organisation", "university-adhd", "sleep-routine"],
    suburb: "Robina",
    practice: "Robina Example Occupational Therapy",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-29",
    focus: "Household organisation, study systems and daily routines",
    matchLine: "Says she works on the household and study side, routines that hold, a system for the flat, and the daily structure a course does not supply.",
    fitSignals: ["Household organisation", "University ADHD", "Routines", "Portuguese"],
    practicalSignals: ["Mixed billing"],
    summary: "Sofia says she works with young adults on household organisation, study systems and daily routines including sleep. She consults in English and Portuguese, on the Gold Coast.",
    about: `Sofia is an invented example occupational therapist. Her profile declares household organisation, study systems and routine work. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Household organisation", "Study systems", "Daily and sleep routines"],
    languages: ["English", "Portuguese"],
    careAreas: ["non-medication"],
    manner: ["structured", "steadying"],
    wheelchairAccessible: true,
    appointmentLength: "Hour-long sessions",
  }),
  example({
    id: "example-liam-kerr",
    name: "Liam Kerr",
    shortName: "Liam",
    gender: "man",
    pronouns: "he/him",
    title: "Exercise physiologist, BExSc",
    profession: "exercise-physiologist",
    expertise: ["exercise-adherence", "sleep-routine"],
    suburb: "Varsity Lakes",
    practice: "Varsity Lakes Example Exercise Physiology",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-31",
    focus: "Movement that sticks, used deliberately for attention and sleep",
    matchLine: "Says he builds movement into a week for people who know it helps and cannot keep it going alone, with attention and sleep as the point, not fitness.",
    fitSignals: ["Keeping exercise going", "Sleep routine", "Accountability"],
    practicalSignals: ["Mixed billing", "Group sessions"],
    summary: "Liam says he works with adults with ADHD on movement that sticks, fixed sessions, company, and a plan built around attention and sleep rather than fitness alone.",
    about: `Liam is an invented example exercise physiologist. His profile declares exercise adherence and sleep-routine work. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Exercise programmes for adults with ADHD", "Movement and sleep"],
    languages: ["English"],
    careAreas: ["non-medication"],
    manner: ["motivating", "structured"],
    wheelchairAccessible: true,
    appointmentLength: "Forty-five-minute sessions",
  }),
  example({
    id: "example-amara-osei",
    name: "Amara Osei",
    shortName: "Amara",
    gender: "woman",
    pronouns: "she/her",
    title: "Exercise physiologist, MClinExPhys",
    profession: "exercise-physiologist",
    expertise: ["exercise-adherence", "stimulant-appetite-concerns"],
    suburb: "Chatswood",
    practice: "Chatswood Example Exercise Physiology",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-26",
    focus: "Exercise and eating alongside stimulant medication",
    matchLine: "Says she works with people whose appetite has changed on medication and who want movement and meals to hold together.",
    fitSignals: ["Keeping exercise going", "Appetite on stimulants", "Telehealth"],
    practicalSignals: ["Mixed billing", "Telehealth follow-ups"],
    summary: "Amara says she works with adults on keeping exercise going and on eating regularly when stimulant medication has changed appetite. First appointments can be by telehealth.",
    about: `Amara is an invented example exercise physiologist. Her profile declares exercise adherence and appetite-on-stimulants work. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Exercise adherence", "Movement and eating alongside stimulant medication"],
    languages: ["English"],
    careAreas: ["non-medication"],
    manner: ["steadying", "collaborative"],
    wheelchairAccessible: true,
    telehealthFirstAppointment: true,
    appointmentLength: "Forty-five-minute sessions",
  }),
  example({
    id: "example-tom-halloran",
    name: "Tom Halloran",
    shortName: "Tom",
    gender: "man",
    pronouns: "he/him",
    title: "ADHD coach, PAAC-certified",
    profession: "adhd-coach",
    expertise: ["deadline-management", "task-initiation", "adhd-work-systems"],
    suburb: "Double Bay",
    practice: "Double Bay Example Coaching",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-09-02",
    focus: "Accountability over weeks: goals, first actions, check-ins",
    matchLine: "Says he provides the external accountability that works for many people with ADHD, weekly goals, first actions, and a check-in somebody is waiting for.",
    fitSignals: ["Deadline management", "Task initiation", "Accountability", "Telehealth"],
    practicalSignals: ["Private fees", "Telehealth follow-ups"],
    summary: "Tom says he coaches adults with ADHD over weeks: goals, first physical actions, artificial milestones and a weekly check-in. Sessions are by telehealth.",
    about: `Tom is an invented example ADHD coach. His profile declares accountability coaching on deadlines and task initiation. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["ADHD coaching for adults", "Deadline and milestone systems"],
    languages: ["English"],
    careAreas: ["non-medication"],
    manner: ["motivating", "structured"],
    wheelchairAccessible: true,
    telehealthFirstAppointment: true,
    appointmentLength: "Forty-five-minute sessions",
  }),
  example({
    id: "example-nadia-rahman",
    name: "Nadia Rahman",
    shortName: "Nadia",
    gender: "woman",
    pronouns: "she/her",
    title: "ADHD coach, ICF-accredited",
    profession: "adhd-coach",
    expertise: ["university-adhd", "household-organisation", "task-initiation"],
    suburb: "Coolangatta",
    practice: "Coolangatta Example Coaching",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-24",
    focus: "Students and early-career adults building structure from scratch",
    matchLine: "Says she coaches students and people in their first jobs on the structure a course or a workplace does not give them.",
    fitSignals: ["University ADHD", "Household organisation", "Task initiation", "Bengali"],
    practicalSignals: ["Private fees", "Telehealth follow-ups"],
    summary: "Nadia says she coaches students and early-career adults on structure, starting and the household side of independent life. She works in English and Bengali, by telehealth or in rooms.",
    about: `Nadia is an invented example ADHD coach. Her profile declares coaching for students and early-career adults on structure and starting. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Coaching university students", "Early-career structure and task initiation"],
    languages: ["English", "Bengali"],
    careAreas: ["non-medication"],
    manner: ["motivating", "collaborative"],
    wheelchairAccessible: false,
    telehealthFirstAppointment: true,
    appointmentLength: "Forty-five-minute sessions",
  }),
  example({
    id: "example-ruth-abernethy",
    name: "Ruth Abernethy",
    shortName: "Ruth",
    gender: "woman",
    pronouns: "she/her",
    title: "Psychiatrist, FRANZCP",
    profession: "psychiatrist",
    expertise: ["medication-review", "late-diagnosis", "emotional-regulation"],
    suburb: "Newcastle",
    practice: "Newcastle Example Psychiatry",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-09-04",
    focus: "The complicated picture: ADHD beside other conditions, and medication that has not settled",
    matchLine: "Says she takes GP referrals where the picture is complicated, other conditions alongside ADHD, or medication that has not settled after a fair trial.",
    fitSignals: ["Medication review", "Late recognition", "Emotional regulation", "Telehealth"],
    practicalSignals: ["GP referral needed", "Telehealth follow-ups"],
    summary: "Ruth says she sees adults on GP referral when ADHD sits beside anxiety, low mood or a long history, and when medication questions have outgrown a general practice. First appointments can be by telehealth.",
    about: `Ruth is an invented example psychiatrist. Her profile declares second-opinion assessment and medication review on GP referral, with shared care back to the GP. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Adult ADHD beside anxiety and low mood", "Medication review and shared care with GPs"],
    languages: ["English"],
    careAreas: ["adhd-assessment", "titration", "shared-care", "anxiety", "depression", "complex-mental-health"],
    manner: ["unhurried", "collaborative"],
    wheelchairAccessible: true,
    telehealthFirstAppointment: true,
    appointmentLength: "Ninety-minute first appointment",
  }),
  example({
    id: "example-sofia-marchetti",
    name: "Sofia Marchetti",
    shortName: "Sofia",
    gender: "woman",
    pronouns: "she/her",
    title: "Accredited Practising Dietitian",
    profession: "dietitian",
    expertise: ["regular-eating", "stimulant-appetite-concerns", "household-organisation"],
    suburb: "Marrickville",
    practice: "Marrickville Example Nutrition",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-09-01",
    focus: "Regular eating when hunger arrives late, and food on medication days",
    matchLine: "Says she works with adults with ADHD on eating that does not depend on feeling hungry, anchors, no-cook food, and appetite on medication days.",
    fitSignals: ["Regular eating", "Appetite on stimulants", "Household organisation", "Italian"],
    practicalSignals: ["Private fees", "Telehealth follow-ups"],
    summary: "Sofia says she helps adults with ADHD eat regularly when the hunger signal arrives late or medication flattens it during the day: meal anchors, food within reach, and a kitchen that needs no planning. She works in English and Italian.",
    about: `Sofia is an invented example dietitian. Her profile declares work on regular eating, appetite on medication days and the household side of food. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Regular eating with ADHD", "Appetite on stimulant medication", "Low-planning kitchens"],
    languages: ["English", "Italian"],
    careAreas: ["non-medication"],
    manner: ["non_judgmental", "structured"],
    wheelchairAccessible: true,
    telehealthFirstAppointment: true,
    appointmentLength: "Sixty-minute first appointment",
  }),
  example({
    id: "example-marcus-webb",
    name: "Marcus Webb",
    shortName: "Marcus",
    gender: "man",
    pronouns: "he/him",
    title: "Relationship counsellor, MCouns",
    profession: "relationship-counsellor",
    expertise: ["adhd-couples", "household-organisation", "emotional-regulation"],
    suburb: "Paddington",
    practice: "Paddington Example Relationship Counselling",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-08-29",
    focus: "Couples where one partner has ADHD: the household load and the reminder argument",
    matchLine: "Says he sees couples where one of you has ADHD and the same argument keeps coming round, the load, the reminders, the sting of being reminded.",
    fitSignals: ["ADHD in couples", "Household organisation", "Emotional regulation", "Evening appointments"],
    practicalSignals: ["Private fees", "Evening appointments"],
    summary: "Marcus says he works with both partners in the room on what ADHD does to a household: who carries what, how reminders land, and how to argue about the system instead of each other. Evening appointments are available.",
    about: `Marcus is an invented example relationship counsellor. His profile declares couples work where one partner has ADHD, in rooms or by telehealth. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Couples counselling where one partner has ADHD", "Household load and division of labour"],
    languages: ["English"],
    careAreas: ["emotional-regulation", "non-medication"],
    manner: ["attuned", "steadying"],
    wheelchairAccessible: false,
    telehealthFirstAppointment: true,
    appointmentLength: "Seventy-five-minute sessions",
  }),
  example({
    id: "example-anil-krishnan",
    name: "Anil Krishnan",
    shortName: "Anil",
    gender: "man",
    pronouns: "he/him",
    title: "Sleep physician, FRACP",
    profession: "sleep-clinician",
    expertise: ["sleep-routine", "medication-review"],
    suburb: "Parramatta",
    practice: "Parramatta Example Sleep Clinic",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-09-03",
    focus: "The late body clock, and the sleep conditions that can sit beside ADHD",
    matchLine: "Says he sees adults with ADHD whose nights will not start, and checks for the sleep conditions that can sit beside it before anything is called a routine problem.",
    fitSignals: ["Sleep routine", "Medication review", "GP referral", "Tamil"],
    practicalSignals: ["GP referral needed", "Mixed billing"],
    summary: "Anil says he sees adults on GP referral when a month of routine changes has not moved their sleep: the late body clock, and the checks for snoring and breathing that a routine cannot fix. He works in English and Tamil.",
    about: `Anil is an invented example sleep physician. His profile declares body-clock work and sleep-condition checks for adults with ADHD, on GP referral. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Delayed sleep phase in adults with ADHD", "Sleep studies and the conditions that sit beside ADHD"],
    languages: ["English", "Tamil"],
    careAreas: ["shared-care", "non-medication"],
    manner: ["sense_making", "unhurried"],
    wheelchairAccessible: true,
    telehealthFirstAppointment: true,
    appointmentLength: "Forty-five-minute first appointment",
  }),
  example({
    id: "example-jess-taumalolo",
    name: "Jess Taumalolo",
    shortName: "Jess",
    gender: "woman",
    pronouns: "she/her",
    title: "Accessibility adviser, university student support",
    profession: "university-support",
    expertise: ["university-adhd", "deadline-management", "workplace-adjustments"],
    suburb: "Kensington",
    practice: "Example University Accessibility Service",
    acceptingNewPatients: true,
    capacityDeclaredAt: "2026-09-05",
    focus: "Study adjustments on paper: extensions, exam arrangements, note-taking",
    matchLine: "Says she puts the adjustment on paper, extensions, exam arrangements, note-taking, so a student with ADHD is not asking each lecturer from scratch.",
    fitSignals: ["University ADHD", "Deadline management", "Adjustments on paper", "No fee"],
    practicalSignals: ["No fee for enrolled students", "Telehealth follow-ups"],
    summary: "Jess says she helps enrolled students register ADHD with the accessibility service and set up the adjustments that follow: extensions, exam arrangements, note-taking and a plan the faculty can see. There is no fee for enrolled students.",
    about: `Jess is an invented example accessibility adviser at a university student support service. Her profile declares registration and study adjustments for students with ADHD. ${SYNTHETIC_ABOUT_NOTICE}`,
    experience: ["Accessibility registration for students with ADHD", "Exam and deadline adjustments"],
    languages: ["English", "Tongan"],
    careAreas: ["non-medication"],
    manner: ["structured", "culturally_attuned"],
    wheelchairAccessible: true,
    telehealthFirstAppointment: true,
    appointmentLength: "Forty-five-minute first appointment",
  }),
];

/**
 * The roster the finder ranks while the tickbox is ON: the real entries first in source order,
 * then the personas. Source order is NOT display order — `rankClinicians` sorts it — this is
 * just the honest construction: nothing here removes or reorders a real entry.
 */
export const demoRoster: readonly Clinician[] = [...clinicians, ...SYNTHETIC_CLINICIANS, ...ALLIED_CLINICIANS];

/** O222: the one choice expression for "which roster is in use" — both the render path and the
 * toggle handler read this, so a future change to what the tickbox composes cannot land in one
 * branch only. */
export const rosterFor = (includeSynthetic: boolean): readonly Clinician[] =>
  includeSynthetic ? demoRoster : clinicians;
