// The runs (docs/adhd-life/PLAY-PLAN.md §2): the modules as micro-games. Phase P1 converts three;
// each keeps the module id, targets, professions, strategy id and insight id of its nine-stage
// original in `interactive.ts`, so the personal model reads a run exactly as it read the module.

import { INTERACTIVE_MODULES, type InteractiveModule } from "./interactive";
import type { Run } from "./play";

function original(id: string): InteractiveModule {
  const m = INTERACTIVE_MODULES.find((x) => x.id === id);
  if (!m) throw new Error(`runs: no module ${id}`);
  return m;
}
const insightOf = (id: string) => { const s = original(id).steps.find((x) => x.kind === "insight"); if (!s || s.kind !== "insight") throw new Error(`runs: ${id} has no insight`); return s; };
const nextOf = (id: string) => { const s = original(id).steps.find((x) => x.kind === "next"); if (!s || s.kind !== "next") throw new Error(`runs: ${id} has no next`); return s; };
const strategyOf = (id: string, strategyId: string) => { for (const s of original(id).steps) if (s.kind === "strategy") { const f = s.strategies.find((x) => x.id === strategyId); if (f) return f; } throw new Error(`runs: ${id} has no strategy ${strategyId}`); };

export const RUNS: readonly Run[] = [
  {
    id: "context",
    title: "Same brain, five scenes",
    tagline: "Why ADHD looks different depending on the situation",
    minutes: 4,
    bean: "alex",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "class", mechanic: "hold", instruction: "Hold to stay in the class discussion. Alex loves this.", seconds: 6, who: "alex", mood: "engaged", prop: "lecture", items: ["phone", "window", "a thought"], hit: "Easy. Interest holds attention on its own.", miss: "Even here it slips sometimes. Interest usually brings it back." },
      { id: "essay", mechanic: "tap", instruction: "Three weeks out. Which can Alex actually start?", seconds: 7, who: "alex", mood: "anxious", prop: "desk", options: [{ id: "essay", label: "The essay" }, { id: "tab", label: "A new tab", correct: true }, { id: "snack", label: "A snack", correct: true }], hit: "Yes. Far off and vague, the essay cannot start. Anything else can.", miss: "Not tonight. Far off and vague, the essay has nothing to grab." },
      { id: "tomorrow", mechanic: "timing", instruction: "Tap the moment the essay becomes real.", seconds: 8, who: "alex", mood: "surprised", prop: "phone", hit: "“Due tomorrow.” Now it is real, and Alex writes all night.", miss: "It became real the night before. Time sense has two settings: now, and not now." },
      { id: "bill", mechanic: "drag-capture", instruction: "Drag the bill somewhere it will be seen.", seconds: 6, who: "alex", mood: "neutral", prop: "bill", items: ["Electricity bill"], hit: "Out of sight was out of mind. In sight, it gets paid.", miss: "It slid out of view for a fortnight. A late fee arrives." },
      { id: "sport", mechanic: "hold", instruction: "Hold to track the ball. Ninety minutes, easy.", seconds: 6, who: "alex", mood: "pleased", prop: "ball", items: ["crowd", "a thought"], hit: "Ninety minutes of complete focus. Same brain as the essay.", miss: "Even sport slips on a bad day. Usually it holds." },
      { id: "same-person", mechanic: "sort", instruction: "What switched Alex on? Sort each into its layer.", seconds: 9, who: "alex", mood: "thinking", options: [{ id: "deadline", label: "A close deadline", layer: "environment" }, { id: "interest", label: "Interest", layer: "brain" }, { id: "teammates", label: "Teammates", layer: "people" }], hit: "None of it was effort. The conditions changed, and so did the brain.", miss: "Close — they all live outside the task. Change the conditions, change the brain." },
      { id: "kitchen-night", mechanic: "recall", instruction: "Mum lists four jobs while the TV is on. Keep them.", seconds: 9, who: "alex", mood: "neutral", prop: "kitchen", items: ["Bins", "Feed the cat", "Text Nan", "Lock the back door"], options: [{ id: "milk", label: "Milk" }, { id: "post", label: "The post" }], hit: "Held, this time. Same brain that lost the essay for three weeks.", miss: "Two fell. Not carelessness: the room was loud and the table small." },
      { id: "your-switch", mechanic: "pick-bean", instruction: "Which bean is you? What switches you on most?", seconds: 10, who: "alex", mood: "thinking", writes: { question: "switch", multi: true }, options: [{ id: "deadline", label: "A close deadline", bean: "alex" }, { id: "interest", label: "Being interested", bean: "priya" }, { id: "company", label: "Somebody beside me", bean: "jordan" }, { id: "clear", label: "A very clear task", bean: "maya" }], hit: "Noted. That is a condition you can borrow on purpose.", miss: "Noted. That is a condition you can borrow on purpose." },
    ],
    insight: insightOf("context"),
    strategy: strategyOf("context", "conditions-map"),
    next: nextOf("context"),
  },
  {
    id: "starting",
    title: "The blank page",
    tagline: "Why starting can be harder than doing",
    minutes: 4,
    bean: "maya",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "coffee", mechanic: "dont-tap", instruction: "Do not tap the coffee. The summary is due at ten.", seconds: 6, who: "maya", mood: "anxious", prop: "desk", options: [{ id: "coffee", label: "Make a coffee" }], hit: "Held. The pull to do anything else is the threshold, not laziness.", miss: "Coffee. Then messages. Then the weather. It is 9:40 and the page is blank." },
      { id: "first-move", mechanic: "order", instruction: "Tap the three moves in order, smallest first.", seconds: 8, who: "maya", mood: "thinking", prop: "desk", options: [{ id: "open", label: "Open the file" }, { id: "title", label: "Type the title" }, { id: "sentence", label: "Write one bad sentence" }], hit: "Tiny, physical, in order. The threshold drops with every move.", miss: "Smallest first. Open the file is a door; the summary is a wall." },
      { id: "help", mechanic: "tap", instruction: "What would actually help Maya start right now?", seconds: 7, who: "maya", mood: "anxious", options: [{ id: "harder", label: "Try harder" }, { id: "bad", label: "Write it badly", correct: true }, { id: "later", label: "Wait to feel ready" }, { id: "person", label: "Sit beside somebody", correct: true }], hit: "Yes. Lower the threshold: a bad first line, or a person in the room.", miss: "Effort was never the missing piece. Lower the threshold instead." },
      { id: "vague", mechanic: "tap", instruction: "Which task is hardest to begin?", seconds: 6, who: "maya", mood: "overwhelmed", prop: "desk", options: [{ id: "improve", label: "Improve the report", correct: true }, { id: "title", label: "Write the title" }], hit: "Vague, big, judged: that is where the threshold is highest.", miss: "The title has a first action built in. “Improve” has to be designed first." },
      { id: "company", mechanic: "hold", instruction: "A friend sits down. Hold to keep going.", seconds: 6, who: "maya", mood: "engaged", prop: "desk", items: ["phone", "email"], hit: "Company lowers the threshold in a way willpower does not.", miss: "Even with company it slips. Usually a person in the room is enough." },
      { id: "tiny-clock", mechanic: "timing", instruction: "Tap when the ten-minute timer makes starting feel possible.", seconds: 8, who: "maya", mood: "thinking", prop: "phone", options: [{ id: "hour", label: "An hour blocked out" }, { id: "ten", label: "Ten minutes, then stop", correct: true }, { id: "whenever", label: "Whenever I feel ready" }], hit: "Ten minutes is a door. An hour is a wall.", miss: "Ten minutes was the moment. Small enough to begin, allowed to stop." },
      { id: "layers", mechanic: "sort", instruction: "What raised the threshold this morning? Sort each into its layer.", seconds: 10, who: "maya", mood: "overwhelmed", options: [{ id: "vague", label: "A vague brief", layer: "environment" }, { id: "night", label: "Five hours’ sleep", layer: "body" }, { id: "judge", label: "A manager who will judge it", layer: "people" }], hit: "None of that is effort. Three layers, three levers.", miss: "Close. The brief is environment, the sleep is body, the judging is people." },
      { id: "your-hardest", mechanic: "pick-bean", instruction: "Which bean is you? What is hardest to start?", seconds: 10, who: "maya", mood: "thinking", writes: { question: "hardest-to-start", multi: true }, options: [{ id: "vague", label: "Vague ones", bean: "maya" }, { id: "big", label: "Big ones", bean: "alex" }, { id: "boring", label: "Boring ones", bean: "jordan" }, { id: "judged", label: "Ones somebody will judge", bean: "priya" }], hit: "Noted. Your threshold has a shape, and shapes can be worked around.", miss: "Noted. Your threshold has a shape, and shapes can be worked around." },
    ],
    insight: insightOf("starting"),
    strategy: strategyOf("starting", "first-physical-action"),
    next: nextOf("starting"),
  },
  {
    id: "working-memory",
    title: "The small table",
    tagline: "Why four things become two",
    minutes: 4,
    bean: "jordan",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "four", mechanic: "recall", instruction: "Four things. Read them once, then the phone buzzes.", seconds: 8, who: "jordan", mood: "neutral", prop: "kitchen", items: ["Milk", "The parcel", "Stamps", "Sam’s script"], hit: "All four. Under stress or after a short night, the table is smaller.", miss: "Some fell off. Forgetting is the table being knocked, not carelessness." },
      { id: "buzz", mechanic: "dont-tap", instruction: "Do not open the group chat until the shops.", seconds: 6, who: "jordan", mood: "anxious", prop: "phone", options: [{ id: "chat", label: "Open the chat" }], hit: "Held. Every interruption clears part of the table.", miss: "Opened. It clears part of the table, and you do not notice which part." },
      { id: "capture", mechanic: "drag-capture", instruction: "Sam asks for two more things. Drag each onto the note.", seconds: 7, who: "jordan", mood: "thinking", prop: "kitchen", items: ["Bin day", "Call the landlord"], hit: "Off the table, onto the note. Now it cannot be knocked.", miss: "Held in the head, and gone by the door. The note would have kept it." },
      { id: "knocks", mechanic: "swipe", instruction: "Swipe away what knocks things off the table.", seconds: 7, who: "jordan", mood: "overwhelmed", items: ["Phone", "A colleague", "A thought", "Tired"], hit: "Cleared. Knowing what knocks the table is half the fix.", miss: "Too many at once. That is exactly the moment things fall." },
      { id: "why", mechanic: "tap", instruction: "Jordan forgot the stamps. What is true?", seconds: 6, who: "jordan", mood: "embarrassed", options: [{ id: "care", label: "Jordan does not care" }, { id: "table", label: "The table was knocked", correct: true }], hit: "Forgetting is not the same as not caring. It never was.", miss: "Jordan cared. The table was knocked. Those are different things." },
      { id: "door-list", mechanic: "order", instruction: "Leaving the house. Tap the check in order.", seconds: 8, who: "jordan", mood: "neutral", prop: "door", options: [{ id: "keys", label: "Keys" }, { id: "phone", label: "Phone" }, { id: "note", label: "The note" }], hit: "Keys, phone, note. The same three at the door, every time.", miss: "Keys, phone, note. A fixed order means nothing has to be remembered." },
      { id: "two-sides", mechanic: "flip", instruction: "The stamps again. Tap each of them, then what is true.", seconds: 12, who: "sam", mood: "frustrated", options: [{ id: "jordan", label: "Jordan", bean: "jordan", thought: "I had it. Then the phone went, and the stamps were just gone." }, { id: "sam", label: "Sam", bean: "sam", thought: "Third time. I start to wonder if it matters to them at all." }], hit: "Both true. A knocked table looks like not caring from outside.", miss: "Both are true. From inside it was a knock; from outside, indifference." },
      { id: "your-knocks", mechanic: "pick-bean", instruction: "What most often knocks your table?", seconds: 10, who: "jordan", mood: "thinking", writes: { question: "knocks", multi: true }, options: [{ id: "phone", label: "My phone", bean: "alex" }, { id: "people", label: "People talking to me", bean: "sam" }, { id: "own-thoughts", label: "My own thoughts", bean: "priya" }, { id: "tired", label: "Being tired", bean: "jordan" }], hit: "Noted. That is where a capture place earns its keep.", miss: "Noted. That is where a capture place earns its keep." },
    ],
    insight: insightOf("working-memory"),
    strategy: strategyOf("working-memory", "one-capture-place"),
    next: nextOf("working-memory"),
  },

  // ── Understand ADHD ─────────────────────────────────────────────────────────────────────
  {
    id: "more-than-attention",
    title: "Not just attention",
    tagline: "Four things wearing attention’s name",
    minutes: 4,
    bean: "maya",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "review", mechanic: "tap", instruction: "“You just need to focus more.” Was that the problem?", seconds: 7, who: "maya", mood: "frustrated", prop: "desk", options: [{ id: "yes", label: "Yes, focus" }, { id: "no", label: "No — something else", correct: true }], hit: "Maya focused nine hours yesterday. Focus was never the missing piece.", miss: "She focused nine hours yesterday. The report was late for other reasons." },
      { id: "brief", mechanic: "drag-capture", instruction: "The brief is about to vanish. Get it onto the note.", seconds: 6, who: "maya", mood: "anxious", prop: "desk", items: ["The brief"], hit: "Working memory: it stayed because it left her head.", miss: "Gone. That was working memory, not attention." },
      { id: "time", mechanic: "timing", instruction: "Tap when the data work becomes real.", seconds: 8, who: "maya", mood: "thinking", prop: "calendar", hit: "Only when it is close. Time sense: now, and not now.", miss: "It felt far until it was not. Time sense, not attention." },
      { id: "email", mechanic: "pause", instruction: "A sharp email lands. Hold until it cools, then open the file.", seconds: 8, who: "maya", mood: "overwhelmed", prop: "phone", hit: "Fast in, slow out. The pause is the skill.", miss: "The sting arrived fast and the file stayed shut. That is emotion." },
      { id: "name-it", mechanic: "sort", instruction: "Sort each moment into the layer it lives in.", seconds: 10, who: "maya", mood: "thinking", options: [{ id: "brief", label: "Forgot the brief", layer: "brain" }, { id: "late", label: "Sharp email", layer: "people" }, { id: "structure", label: "No check-ins", layer: "environment" }], hit: "Three functions, three layers, none of them ‘focus’.", miss: "Close. Memory is brain; the email is people; check-ins are environment." },
      { id: "hot-start", mechanic: "timing", instruction: "Tap the moment the report becomes possible to start.", seconds: 8, who: "maya", mood: "anxious", prop: "desk", options: [{ id: "vague", label: "“Make it better”" }, { id: "defined", label: "“Fix the two charts by Friday”", correct: true }, { id: "ready", label: "When I feel ready" }], hit: "Defined and close. Activation, not attention, was the missing piece.", miss: "It became possible when it was defined. That is activation." },
      { id: "brief-again", mechanic: "recall", instruction: "The manager lists three changes in passing. Keep them.", seconds: 9, who: "maya", mood: "neutral", prop: "desk", items: ["Shorter intro", "Two charts", "Send by Friday"], options: [{ id: "font", label: "A new font" }, { id: "title", label: "A new title" }], hit: "Held. On a busy day, this is the function that drops first.", miss: "One fell. Working memory, not attention, is what let go." },
      { id: "your-cost", mechanic: "pick-bean", instruction: "Which costs you most?", seconds: 10, who: "maya", mood: "thinking", writes: { question: "hardest-part" }, options: [{ id: "starting", label: "Starting", bean: "maya" }, { id: "memory", label: "Remembering", bean: "jordan" }, { id: "time", label: "Time", bean: "alex" }, { id: "emotion", label: "Emotion", bean: "priya" }], hit: "Noted. That function has its own run.", miss: "Noted. That function has its own run." },
    ],
    insight: insightOf("more-than-attention"),
    strategy: strategyOf("more-than-attention", "name-the-function"),
    next: nextOf("more-than-attention"),
  },
  {
    id: "deadlines",
    title: "Now and not-now",
    tagline: "Why the night before works",
    minutes: 4,
    bean: "alex",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "rumour", mechanic: "dont-tap", instruction: "Three weeks out. Do not tap the essay.", seconds: 5, who: "alex", mood: "neutral", prop: "calendar", options: [{ id: "essay", label: "Start the essay" }], hit: "Right. It is not real yet, and nothing starts.", miss: "Started at three weeks? Rare. It usually is not real yet." },
      { id: "real", mechanic: "timing", instruction: "Tap the moment it crosses into now.", seconds: 8, who: "alex", mood: "surprised", prop: "phone", hit: "The night before. Everything switches on at once.", miss: "It crossed the night before. Two settings: now, not now." },
      { id: "pour", mechanic: "hold", instruction: "Hold. The essay pours out, all night.", seconds: 6, who: "alex", mood: "engaged", prop: "desk", items: ["sleep", "a shift", "tomorrow"], hit: "Good work, high cost: a sleepless night and a missed shift.", miss: "Even then it slips. Usually the pressure holds it." },
      { id: "why", mechanic: "tap", instruction: "What actually changed between week one and the night before?", seconds: 7, who: "alex", mood: "thinking", options: [{ id: "care", label: "Alex started caring" }, { id: "distance", label: "The distance", correct: true }, { id: "fear", label: "Fear" }], hit: "Alex cared all along. The deadline moved into now.", miss: "Caring never changed. The distance did." },
      { id: "milestone", mechanic: "order", instruction: "Build a milestone. Tap the steps in order.", seconds: 8, who: "alex", mood: "pleased", prop: "calendar", options: [{ id: "piece", label: "Pick one small piece" }, { id: "date", label: "Make it due in two days" }, { id: "person", label: "Tell someone who will wait for it" }], hit: "That brings now forward. The strength stays, the cost shrinks.", miss: "Piece, date, person. Each one brings now a little closer." },
      { id: "see-it", mechanic: "drag-capture", instruction: "Three weeks is invisible. Drag the essay somewhere you will see it.", seconds: 6, who: "alex", mood: "neutral", prop: "calendar", items: ["Essay, due 24th"], hit: "On the wall, it exists. In the head, it does not until the night before.", miss: "Out of sight, and not-now. It reappears the night before." },
      { id: "layers", mechanic: "sort", instruction: "What brought ‘now’ closer? Sort each into its layer.", seconds: 10, who: "alex", mood: "thinking", options: [{ id: "milestone", label: "A two-day milestone", layer: "environment" }, { id: "friend", label: "A friend waiting for it", layer: "people" }, { id: "sleep", label: "A full night’s sleep", layer: "body" }], hit: "Now was moved from outside. Time sense stayed the same.", miss: "Milestone is environment, the friend is people, the sleep is body." },
      { id: "your-horizon", mechanic: "pick-bean", instruction: "How close before a deadline feels real to you?", seconds: 10, who: "alex", mood: "thinking", writes: { question: "horizon" }, options: [{ id: "day", label: "The day before", bean: "alex" }, { id: "days", label: "A few days", bean: "maya" }, { id: "week", label: "About a week", bean: "priya" }, { id: "varies", label: "It varies", bean: "jordan" }], hit: "Noted. That is how wide your milestones need to be.", miss: "Noted. That is how wide your milestones need to be." },
    ],
    insight: insightOf("deadlines"),
    strategy: strategyOf("deadlines", "artificial-milestones"),
    next: nextOf("deadlines"),
  },
  {
    id: "hyperfocus",
    title: "The vanishing hours",
    tagline: "Deep focus that needs steering",
    minutes: 3,
    bean: "priya",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "formula", mechanic: "hold", instruction: "Hold to fix one formula. Just one.", seconds: 7, who: "priya", mood: "engaged", prop: "desk", items: ["lunch", "a call", "the report"], hit: "Seven hours later. The spreadsheet is magnificent.", miss: "Even hyperfocus slips sometimes. Usually it locks for hours." },
      { id: "cost", mechanic: "swipe", instruction: "Clear what it cost while she was locked in.", seconds: 7, who: "priya", mood: "surprised", items: ["A missed call", "No lunch", "The real report"], hit: "The focus was not the problem. Its aim was.", miss: "Too much fell. The focus was fine; the aim was not." },
      { id: "steer", mechanic: "tap", instruction: "Is hyperfocus a strength or a problem?", seconds: 6, who: "priya", mood: "thinking", options: [{ id: "strength", label: "Strength" }, { id: "problem", label: "Problem" }, { id: "both", label: "Both", correct: true }], hit: "A strength with poor steering. Aim it, and set an edge.", miss: "Both. Seven hours of depth, pointed at the wrong thing." },
      { id: "edge", mechanic: "order", instruction: "Set an edge before starting. Tap the steps in order.", seconds: 8, who: "priya", mood: "pleased", prop: "desk", options: [{ id: "alarm", label: "Set the stop alarm" }, { id: "note", label: "Write the next thing beside you" }, { id: "stand", label: "Stand up when it rings" }], hit: "An external clock, because hyperfocus has none.", miss: "Alarm, note, stand. The clock has to live outside your head." },
      { id: "alarm", mechanic: "timing", instruction: "The stop alarm rings. Tap the moment to stand up.", seconds: 8, who: "priya", mood: "engaged", prop: "desk", options: [{ id: "ignore", label: "After this one formula" }, { id: "now", label: "When it rings", correct: true }, { id: "later", label: "At a natural pause" }], hit: "On the ring. There is no natural pause inside hyperfocus.", miss: "When it rang. ‘One more’ is how seven hours happen." },
      { id: "aim", mechanic: "drag-capture", instruction: "Before you dive, drag the real task onto the note.", seconds: 6, who: "priya", mood: "thinking", prop: "desk", items: ["The report, section 2"], hit: "Aimed. The depth now lands where it is needed.", miss: "Unaimed, the depth landed on the spreadsheet. Beautiful, and beside the point." },
      { id: "your-target", mechanic: "pick-bean", instruction: "Where does your hyperfocus usually land?", seconds: 10, who: "priya", mood: "thinking", writes: { question: "lands-on", multi: true }, options: [{ id: "work", label: "The right work", bean: "priya" }, { id: "side", label: "A side task", bean: "maya" }, { id: "hobby", label: "A hobby or game", bean: "alex" }, { id: "research", label: "Researching something", bean: "jordan" }], hit: "Noted. That is where the target needs writing down first.", miss: "Noted. That is where the target needs writing down first." },
    ],
    insight: insightOf("hyperfocus"),
    strategy: strategyOf("hyperfocus", "external-edge"),
    next: nextOf("hyperfocus"),
  },
  // ── Work & Study ─────────────────────────────────────────────────────────────────────────
  {
    id: "ambiguity",
    title: "Improve the presentation",
    tagline: "Vague tasks and why they stay untouched",
    minutes: 4,
    bean: "maya",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "which", mechanic: "tap", instruction: "Which is easier to begin?", seconds: 6, who: "maya", mood: "overwhelmed", prop: "desk", options: [{ id: "improve", label: "Improve the presentation" }, { id: "title", label: "Write the title slide", correct: true }], hit: "Not smaller. Defined. The first action is built in.", miss: "Most people cannot start ‘improve’. It has to be designed first." },
      { id: "scroll", mechanic: "dont-tap", instruction: "Every slide could be better. Do not open all of them.", seconds: 5, who: "maya", mood: "anxious", prop: "desk", options: [{ id: "all", label: "Open every slide" }], hit: "Held. Ambiguity is what raised the threshold, not the work.", miss: "Opened, scrolled, closed. None got touched." },
      { id: "define", mechanic: "order", instruction: "Turn ‘improve’ into three questions. Tap in order.", seconds: 9, who: "maya", mood: "thinking", options: [{ id: "done", label: "What would make this done?" }, { id: "first", label: "Which part first?" }, { id: "action", label: "What is the first physical action?" }], hit: "Defined, then started. The work was never too hard.", miss: "Done, first, action. Define before you start." },
      { id: "ask", mechanic: "tap", instruction: "Maya messages her manager. Weakness, or the fix?", seconds: 6, who: "maya", mood: "neutral", prop: "phone", options: [{ id: "weak", label: "Weakness" }, { id: "fix", label: "The fix", correct: true }], hit: "One question upstream saves an afternoon downstream.", miss: "It is the fix. Nobody assigned the designing; asking is how it gets done." },
      { id: "first-slide", mechanic: "drag-capture", instruction: "Pick the one slide to fix. Drag it onto the note.", seconds: 6, who: "maya", mood: "thinking", prop: "desk", items: ["Slide 4: the chart"], hit: "One slide is a task. ‘The presentation’ was a fog.", miss: "Unpicked, every slide stays equally untouched." },
      { id: "vague-sort", mechanic: "sort", instruction: "Why did ‘improve it’ stall? Sort each into its layer.", seconds: 10, who: "maya", mood: "overwhelmed", options: [{ id: "brief", label: "No definition of done", layer: "environment" }, { id: "threshold", label: "A high start threshold", layer: "brain" }, { id: "manager", label: "A manager who assumed", layer: "people" }], hit: "Three layers. Only one of them is inside Maya.", miss: "The brief is environment, the threshold is brain, the assuming is people." },
      { id: "your-source", mechanic: "pick-bean", instruction: "Where do your vaguest tasks come from?", seconds: 10, who: "maya", mood: "thinking", writes: { question: "source", multi: true }, options: [{ id: "manager", label: "A manager", bean: "sam" }, { id: "self", label: "Myself", bean: "maya" }, { id: "course", label: "A course", bean: "alex" }, { id: "clients", label: "Clients", bean: "priya" }], hit: "Noted. That is who to ask what done looks like.", miss: "Noted. That is who to ask what done looks like." },
    ],
    insight: insightOf("ambiguity"),
    strategy: strategyOf("ambiguity", "define-done"),
    next: nextOf("ambiguity"),
  },
  {
    id: "interruption",
    title: "Quick one",
    tagline: "Why the return costs more than the interruption",
    minutes: 4,
    bean: "maya",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "inside", mechanic: "hold", instruction: "Twenty minutes in. Hold to stay inside the report.", seconds: 6, who: "maya", mood: "engaged", prop: "desk", items: ["“Quick one?”", "a ping", "a thought"], hit: "In. This is the state an interruption spends.", miss: "Pulled out. Getting back in is the expensive part." },
      { id: "quick", mechanic: "tap", instruction: "“Can you check this? Two secs.” It took three minutes. The return?", seconds: 7, who: "maya", mood: "frustrated", prop: "phone", options: [{ id: "three", label: "Three minutes" }, { id: "forty", label: "Forty minutes", correct: true }], hit: "The rebuild is the cost: where you were, what was next, why.", miss: "Forty. The picture has to be rebuilt in working memory." },
      { id: "breadcrumb", mechanic: "drag-capture", instruction: "Before answering, drop one line onto the note.", seconds: 6, who: "maya", mood: "thinking", prop: "desk", items: ["Section 3 — next: the chart"], hit: "Future Maya reads one line and is back in seconds.", miss: "No breadcrumb. Future Maya starts from nothing." },
      { id: "clear", mechanic: "swipe", instruction: "Protect one hour. Clear what usually gets in.", seconds: 7, who: "maya", mood: "neutral", items: ["Messages", "The desk visit", "Phone"], hit: "One protected block a day beats a quieter world.", miss: "Not all cleared. Even one fewer helps." },
      { id: "pings", mechanic: "dont-tap", instruction: "Inside the report. Do not tap the ping.", seconds: 6, who: "maya", mood: "engaged", prop: "phone", options: [{ id: "ping", label: "See what it was" }], hit: "Held. One ping ignored is forty minutes kept.", miss: "Looked. Three minutes gone, forty to rebuild." },
      { id: "hour", mechanic: "timing", instruction: "Tap the moment to book the protected hour.", seconds: 8, who: "maya", mood: "neutral", prop: "calendar", options: [{ id: "quiet", label: "When it goes quiet" }, { id: "first", label: "First thing, before email", correct: true }, { id: "lunch", label: "Over lunch" }], hit: "Before the day gets in. Quiet never arrives on its own.", miss: "First thing. Waiting for quiet means waiting all day." },
      { id: "your-source", mechanic: "pick-bean", instruction: "What interrupts you most?", seconds: 10, who: "maya", mood: "thinking", writes: { question: "source", multi: true }, options: [{ id: "messages", label: "Messages", bean: "alex" }, { id: "people", label: "People at the desk", bean: "sam" }, { id: "own", label: "My own thoughts", bean: "priya" }, { id: "noise", label: "Noise", bean: "jordan" }], hit: "Noted. That is what the protected block keeps out.", miss: "Noted. That is what the protected block keeps out." },
    ],
    insight: insightOf("interruption"),
    strategy: strategyOf("interruption", "breadcrumb"),
    next: nextOf("interruption"),
  },
  {
    id: "perfectionism",
    title: "It has to be excellent",
    tagline: "The standard that stops the start",
    minutes: 4,
    bean: "priya",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "wall", mechanic: "dont-tap", instruction: "Two weeks to go. Do not read one more source.", seconds: 5, who: "priya", mood: "anxious", prop: "desk", options: [{ id: "read", label: "Read another source" }], hit: "Held. Reading more was the wall dressed as work.", miss: "One more source. The page stays blank. That is the wall." },
      { id: "permission", mechanic: "tap", instruction: "Why can Priya start once the deadline makes excellent impossible?", seconds: 7, who: "priya", mood: "thinking", options: [{ id: "pressure", label: "Pressure" }, { id: "permission", label: "Permission to be rough", correct: true }], hit: "The bar dropped to ‘done’. Done can be started.", miss: "The deadline gave permission to be rough. Nothing else had." },
      { id: "bad-draft", mechanic: "hold", instruction: "Ten minutes. Hold and write the worst version.", seconds: 7, who: "priya", mood: "embarrassed", prop: "desk", items: ["edit it", "delete it", "read it back"], hit: "A bad draft is a door. The standard belongs on the edit.", miss: "Started editing. The standard belongs at the end, not the start." },
      { id: "standard", mechanic: "tap", instruction: "Priya does not know how polished it needs to be. First move?", seconds: 6, who: "priya", mood: "neutral", prop: "phone", options: [{ id: "guess", label: "Aim high, guess" }, { id: "ask", label: "Ask the reader", correct: true }], hit: "Uncertainty about the standard is half the wall. Ask it away.", miss: "Guessing aims high every time. Asking lowers the wall." },
      { id: "bar", mechanic: "timing", instruction: "Tap the moment the bar drops to ‘done’.", seconds: 8, who: "priya", mood: "anxious", prop: "desk", options: [{ id: "weeks", label: "Two weeks out" }, { id: "night", label: "The night before", correct: true }, { id: "never", label: "It never drops" }], hit: "The night before. The deadline gave permission nothing else had.", miss: "It dropped the night before. Permission to be rough came late." },
      { id: "two-sides", mechanic: "flip", instruction: "The reader and the writer. Tap each, then what is true.", seconds: 12, who: "sam", mood: "neutral", options: [{ id: "priya", label: "Priya", bean: "priya", thought: "It has to be excellent or they will see I am not." }, { id: "sam", label: "The reader", bean: "sam", thought: "I need it by Monday and roughly right. Polish is not the point." }], hit: "Both true. The standard in Priya’s head was never the reader’s.", miss: "Both true. The reader wanted rough and on time." },
      { id: "your-standard", mechanic: "pick-bean", instruction: "Do you usually know what standard is expected?", seconds: 8, who: "priya", mood: "thinking", writes: { question: "standard" }, options: [{ id: "yes", label: "Yes", bean: "sam" }, { id: "guess", label: "I guess, and aim high", bean: "priya" }, { id: "no", label: "Rarely", bean: "alex" }], hit: "Noted. That decides which strategy comes first.", miss: "Noted. That decides which strategy comes first." },
    ],
    insight: insightOf("perfectionism"),
    reflect: { prompt: "When did this last stop you starting?", suggestions: ["Knowing the standard", "Permission to be rough", "Less riding on it"] },
    strategy: strategyOf("perfectionism", "bad-first-draft"),
    next: nextOf("perfectionism"),
  },
  // ── Relationships ────────────────────────────────────────────────────────────────────────
  {
    id: "not-listening",
    title: "You’re not listening",
    tagline: "One conversation, two experiences",
    minutes: 4,
    bean: "jordan",
    recognition: "Does this happen in your relationships?",
    rounds: [
      { id: "plan", mechanic: "hold", instruction: "Sam explains the weekend plan. Hold to stay with it.", seconds: 6, who: "jordan", mood: "neutral", prop: "kitchen", items: ["the window", "work", "a thought"], hit: "Stayed. On another night, half of it lands.", miss: "Drifted, and back before you noticed. Half of it landed." },
      { id: "sides", mechanic: "flip", instruction: "Tap each of them. Then tap what is true.", seconds: 12, who: "sam", mood: "frustrated", options: [{ id: "jordan", label: "Jordan", bean: "jordan", thought: "I really thought I was listening. Something pulled, and I was back before I noticed." }, { id: "sam", label: "Sam", bean: "sam", thought: "I told them yesterday. If it mattered, they would remember." }], hit: "Both are genuine. Drift is involuntary; it reads as not caring.", miss: "Both are true. Neither is lying about how it felt." },
      { id: "reads-as", mechanic: "tap", instruction: "From the outside, attention drift looks like…", seconds: 6, who: "sam", mood: "frustrated", options: [{ id: "tired", label: "Tiredness" }, { id: "indifference", label: "Not caring", correct: true }], hit: "Identical from outside, nothing alike from inside. Most conflict starts there.", miss: "It reads as not caring. That gap is where the argument starts." },
      { id: "name", mechanic: "order", instruction: "Make the drift visible. Tap the moves in order.", seconds: 8, who: "jordan", mood: "embarrassed", options: [{ id: "notice", label: "Notice it slipped" }, { id: "say", label: "“Lost that — again please?”" }, { id: "carry", label: "Carry on" }], hit: "Exposing, and far cheaper than nodding.", miss: "Notice, say it, carry on. Cheaper than nodding along." },
      { id: "phone-down", mechanic: "dont-tap", instruction: "Sam is talking. Do not tap the phone.", seconds: 6, who: "jordan", mood: "neutral", prop: "phone", options: [{ id: "phone", label: "Check the phone" }], hit: "Held. A phone nearby doubles the drift.", miss: "Checked. Sam saw it. That is what ‘not listening’ looks like." },
      { id: "layers", mechanic: "sort", instruction: "Why did half of it land? Sort each into its layer.", seconds: 10, who: "jordan", mood: "thinking", options: [{ id: "tired", label: "Up since five", layer: "body" }, { id: "long", label: "A long explanation", layer: "people" }, { id: "tv", label: "The TV on", layer: "environment" }], hit: "Three layers, none of them ‘not caring’.", miss: "Tired is body, the long explanation is people, the TV is environment." },
      { id: "your-who", mechanic: "pick-bean", instruction: "Who most often feels unheard?", seconds: 10, who: "jordan", mood: "thinking", writes: { question: "who", multi: true }, options: [{ id: "partner", label: "A partner", bean: "sam" }, { id: "family", label: "Family", bean: "priya" }, { id: "friends", label: "Friends", bean: "alex" }, { id: "me", label: "Me too", bean: "jordan" }], hit: "Noted. This run is one worth sharing with them.", miss: "Noted. This run is one worth sharing with them." },
    ],
    insight: insightOf("not-listening"),
    strategy: strategyOf("not-listening", "name-the-drift"),
    next: nextOf("not-listening"),
  },
  {
    id: "forgotten-commitments",
    title: "You said you’d book it",
    tagline: "Remembering isn’t the same as caring",
    minutes: 3,
    bean: "jordan",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "yes", mechanic: "drag-capture", instruction: "Monday: “Can you book it?” Put the promise somewhere it stays.", seconds: 6, who: "jordan", mood: "pleased", prop: "phone", items: ["Book the restaurant"], hit: "Captured. A promise in working memory falls; one on a list holds.", miss: "Said yes, meant it, gone by Friday. The restaurant is full." },
      { id: "sides", mechanic: "flip", instruction: "Friday. Tap each of them, then what is true.", seconds: 12, who: "sam", mood: "frustrated", options: [{ id: "jordan", label: "Jordan", bean: "jordan", thought: "I meant it. It just was not there. I did not decide not to." }, { id: "sam", label: "Sam", bean: "sam", thought: "If I do not follow up, it does not happen. I hold everything." }], hit: "Never declined; still not done. Both of them are tired of it.", miss: "Both are true: a vanished promise, and somebody carrying the follow-up." },
      { id: "care", mechanic: "tap", instruction: "Jordan forgot. What does that mean?", seconds: 6, who: "jordan", mood: "embarrassed", options: [{ id: "care", label: "Jordan does not care" }, { id: "memory", label: "The promise fell off the table", correct: true }], hit: "Remembering is not the same as caring. It never was.", miss: "It fell off the table. Caring and remembering are different things." },
      { id: "shared", mechanic: "order", instruction: "Build the shared list. Tap in order.", seconds: 8, who: "sam", mood: "pleased", prop: "calendar", options: [{ id: "one", label: "One shared list" }, { id: "rule", label: "Not made until it is written" }, { id: "add", label: "Add the next one together" }], hit: "Not distrust. The table your working memory does not have.", miss: "List, rule, add. Sharing the system beats policing it." },
      { id: "written", mechanic: "dont-tap", instruction: "“Sure, I’ll book it.” Do not say yes before it is written.", seconds: 6, who: "jordan", mood: "pleased", prop: "phone", options: [{ id: "yes", label: "“Yes, of course”" }], hit: "Held. Not made until it is written: the rule that keeps promises.", miss: "Said yes. Meant it. It has nowhere to live yet." },
      { id: "when-slip", mechanic: "recall", instruction: "Three promises from breakfast. Keep them to Friday.", seconds: 9, who: "jordan", mood: "neutral", prop: "kitchen", items: ["Book the restaurant", "Call the plumber", "Nan’s birthday card"], options: [{ id: "bins", label: "The bins" }, { id: "gym", label: "The gym" }], hit: "All three, this time. On a list they would hold every time.", miss: "One fell by Friday. Not a decision. A table with no room." },
      { id: "your-carries", mechanic: "pick-bean", instruction: "Who ends up carrying the follow-up?", seconds: 8, who: "sam", mood: "neutral", writes: { question: "carries" }, options: [{ id: "partner", label: "A partner", bean: "sam" }, { id: "family", label: "Family", bean: "priya" }, { id: "me", label: "Me, eventually", bean: "jordan" }, { id: "nobody", label: "Nobody — it drops", bean: "alex" }], hit: "Noted. The shared list is as much for them as for you.", miss: "Noted. The shared list is as much for them as for you." },
    ],
    insight: insightOf("forgotten-commitments"),
    strategy: strategyOf("forgotten-commitments", "shared-calendar"),
    next: nextOf("forgotten-commitments"),
  },
  {
    id: "conflict",
    title: "It started about the dishes",
    tagline: "Fast in, slow out",
    minutes: 4,
    bean: "jordan",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "heat", mechanic: "pause", instruction: "Sam mentions the dishes. Hold until it cools, then release.", seconds: 8, who: "jordan", mood: "frustrated", prop: "kitchen", hit: "Cooled before speaking. The pause is the whole skill.", miss: "Too hot too fast. A minute later it was about everything." },
      { id: "sides", mechanic: "flip", instruction: "Twenty minutes later. Tap each, then what is true.", seconds: 12, who: "sam", mood: "anxious", options: [{ id: "jordan", label: "Jordan", bean: "jordan", thought: "It felt like an attack before I could think. By then I had said things." }, { id: "sam", label: "Sam", bean: "sam", thought: "I said one thing about the dishes. I am scared to raise anything now." }], hit: "Emotion arrives before thought. Sam starts editing what she says.", miss: "Both are true. The speed did it, not the feeling." },
      { id: "when", mechanic: "tap", instruction: "When does the pause have to be agreed?", seconds: 6, who: "jordan", mood: "thinking", options: [{ id: "during", label: "During the argument" }, { id: "before", label: "Over a calm cup of tea", correct: true }], hit: "Before the heat. In the heat there is no agreeing.", miss: "Before. Agreed in advance, or it does not exist when needed." },
      { id: "word", mechanic: "order", instruction: "Agree the pause. Tap in order.", seconds: 8, who: "sam", mood: "pleased", options: [{ id: "tell", label: "Say how fast the heat arrives" }, { id: "word", label: "Pick one pause word" }, { id: "back", label: "Say when you will be back" }], hit: "Leaving is not losing. Coming back is the repair.", miss: "Tell, word, back. Whoever pauses also says when they return." },
      { id: "tea", mechanic: "timing", instruction: "Tap the moment to agree the pause word.", seconds: 8, who: "sam", mood: "neutral", prop: "kitchen", options: [{ id: "during", label: "Mid-argument" }, { id: "calm", label: "Over a calm cup of tea", correct: true }, { id: "after", label: "Never, hopefully" }], hit: "Calm first. In the heat there is no agreeing.", miss: "Over tea. Agreed in advance, or it does not exist when needed." },
      { id: "back", mechanic: "order", instruction: "Twenty minutes later. Tap the return in order.", seconds: 8, who: "jordan", mood: "relieved", prop: "door", options: [{ id: "return", label: "Come back when you said" }, { id: "dishes", label: "Start with the dishes only" }, { id: "repair", label: "Say what the heat was about" }], hit: "Return, dishes, repair. Coming back is the repair.", miss: "Return, dishes, repair. Leaving is not losing; not returning is." },
      { id: "your-trigger", mechanic: "pick-bean", instruction: "What most often lights it?", seconds: 10, who: "jordan", mood: "thinking", writes: { question: "trigger", multi: true }, options: [{ id: "criticism", label: "Anything like criticism", bean: "jordan" }, { id: "tired", label: "Tired or hungry", bean: "alex" }, { id: "interrupted", label: "Being interrupted", bean: "maya" }, { id: "unfair", label: "Feeling judged", bean: "priya" }], hit: "Noted. That is the moment the pause word is for.", miss: "Noted. That is the moment the pause word is for." },
    ],
    insight: insightOf("conflict"),
    reflect: { prompt: "When did this last happen?", suggestions: ["A pause", "Being less tired", "Repairing sooner"] },
    strategy: strategyOf("conflict", "agreed-pause"),
    next: nextOf("conflict"),
  },
  // ── Daily Life ───────────────────────────────────────────────────────────────────────────
  {
    id: "household",
    title: "Everything at 80%",
    tagline: "Who is holding the list",
    minutes: 3,
    bean: "jordan",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "eighty", mechanic: "swipe", instruction: "Sunday. Finish the last step of each.", seconds: 7, who: "jordan", mood: "overwhelmed", prop: "kitchen", items: ["Wet washing", "Bins, nearly out", "Half a form"], hit: "Every job has a last step that lives in working memory.", miss: "Three at 80 %. Jordan did a lot, and the flat looks untouched." },
      { id: "wrong", mechanic: "tap", instruction: "What is actually going wrong?", seconds: 6, who: "jordan", mood: "thinking", options: [{ id: "effort", label: "Not enough effort" }, { id: "finishing", label: "Finishing, not starting", correct: true }], hit: "A hundred small tasks, each remembered twice: to start, to finish.", miss: "Effort was plenty. Each job needs remembering twice." },
      { id: "anchor", mechanic: "drag-capture", instruction: "Anchor the bins to something that already happens. Drag it there.", seconds: 6, who: "jordan", mood: "neutral", prop: "kitchen", items: ["Bins out"], hit: "Bins go out when the kettle goes on Tuesday. The anchor remembers.", miss: "Unanchored, it floats until it is forgotten." },
      { id: "visible", mechanic: "tap", instruction: "Where should the form live?", seconds: 6, who: "jordan", mood: "neutral", options: [{ id: "drawer", label: "In a drawer" }, { id: "table", label: "On the table, in view", correct: true }], hit: "Visible states beat hidden ones. A basket, not a drawer.", miss: "The drawer is where things vanish. In view, it gets done." },
      { id: "last-steps", mechanic: "order", instruction: "Finish the washing. Tap the last steps in order.", seconds: 8, who: "jordan", mood: "neutral", prop: "kitchen", options: [{ id: "hang", label: "Hang it out" }, { id: "fold", label: "Fold it" }, { id: "away", label: "Put it away" }], hit: "Three last steps. Each one lives in working memory until it is done.", miss: "Hang, fold, away. The last step is where 80 % happens." },
      { id: "two-sides", mechanic: "flip", instruction: "Sunday night. Tap each of them, then what is true.", seconds: 12, who: "sam", mood: "frustrated", options: [{ id: "jordan", label: "Jordan", bean: "jordan", thought: "I did six things today. Why does it look like nothing?" }, { id: "sam", label: "Sam", bean: "sam", thought: "I am the list. If I stop holding it, everything stops." }], hit: "Both true. The list needs a home that is not Sam’s head.", miss: "Both true. Effort was plenty; the list had no home." },
      { id: "your-holds", mechanic: "pick-bean", instruction: "Who holds the household list?", seconds: 8, who: "sam", mood: "neutral", writes: { question: "holds" }, options: [{ id: "me", label: "Me", bean: "jordan" }, { id: "partner", label: "A partner or flatmate", bean: "sam" }, { id: "nobody", label: "Nobody — chaos", bean: "alex" }, { id: "shared", label: "It is shared", bean: "maya" }], hit: "Noted. Anchors are easier to share than memories.", miss: "Noted. Anchors are easier to share than memories." },
    ],
    insight: insightOf("household"),
    strategy: strategyOf("household", "anchored-routine"),
    next: nextOf("household"),
  },
  // ── Sleep & Body ─────────────────────────────────────────────────────────────────────────
  {
    id: "sleep",
    title: "1:40am",
    tagline: "Why the night gets later",
    minutes: 3,
    bean: "alex",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "arrived", mechanic: "hold", instruction: "1:40am. Quiet at last. Hold to keep working.", seconds: 6, who: "alex", mood: "engaged", prop: "bed", items: ["tomorrow’s 9am", "the video", "3am"], hit: "The world finally supplied quiet. Tomorrow’s 9am pays.", miss: "Even the night slips. Usually the quiet holds it." },
      { id: "why", mechanic: "tap", instruction: "Why now?", seconds: 6, who: "alex", mood: "thinking", prop: "bed", options: [{ id: "owl", label: "Night person" }, { id: "quiet", label: "Nothing is interrupting", correct: true }, { id: "avoid", label: "Avoiding tomorrow" }], hit: "At 1am the world supplies what the day never did.", miss: "Partly a late clock. Mostly: nothing is pulling attention at 1am." },
      { id: "short", mechanic: "swipe", instruction: "A short night. Clear what got bigger.", seconds: 7, who: "alex", mood: "overwhelmed", items: ["Smaller table", "Higher threshold", "Faster heat"], hit: "Every ADHD difficulty is larger after a short night.", miss: "They all got bigger. Sleep sits upstream of the rest." },
      { id: "wake", mechanic: "tap", instruction: "Which moves the clock more?", seconds: 6, who: "alex", mood: "neutral", options: [{ id: "bed", label: "A fixed bedtime" }, { id: "wake", label: "A fixed wake time", correct: true }], hit: "Bedtimes lose to hyperfocus. Wake times drag the clock earlier.", miss: "The wake time. Kept even after a late night, it moves the clock." },
      { id: "stop", mechanic: "timing", instruction: "Tap the moment to close the laptop.", seconds: 8, who: "alex", mood: "engaged", prop: "bed", options: [{ id: "done", label: "When it is finished" }, { id: "alarm", label: "When the alarm says", correct: true }, { id: "tired", label: "When I feel tired" }], hit: "The alarm. Tired never arrives inside hyperfocus.", miss: "When the alarm said. ‘Finished’ is 3am." },
      { id: "morning", mechanic: "dont-tap", instruction: "7am, five hours’ sleep. Do not tap snooze.", seconds: 6, who: "alex", mood: "overwhelmed", prop: "bed", options: [{ id: "snooze", label: "Snooze" }], hit: "Up. The wake time held, and the clock moves earlier tonight.", miss: "Snoozed. The clock drifts later, and tonight goes later too." },
      { id: "your-late", mechanic: "pick-bean", instruction: "What keeps your night going?", seconds: 10, who: "alex", mood: "thinking", writes: { question: "late", multi: true }, options: [{ id: "work", label: "Finally getting work done", bean: "alex" }, { id: "screens", label: "Screens", bean: "jordan" }, { id: "quiet", label: "The quiet", bean: "priya" }, { id: "cannot-stop", label: "I cannot stop", bean: "maya" }], hit: "Noted. The wind-down is the problem, not the falling asleep.", miss: "Noted. The wind-down is the problem, not the falling asleep." },
    ],
    insight: insightOf("sleep"),
    strategy: strategyOf("sleep", "fixed-wake"),
    next: nextOf("sleep"),
  },
  {
    id: "exercise",
    title: "Ran twice last month",
    tagline: "Movement that steadies, and keeping it going",
    minutes: 3,
    bean: "priya",
    recognition: "Does this happen to you?",
    rounds: [
      { id: "clear", mechanic: "tap", instruction: "Priya’s clearest days have one thing in common. What?", seconds: 6, who: "priya", mood: "pleased", prop: "ball", options: [{ id: "coffee", label: "Coffee" }, { id: "run", label: "She ran first", correct: true }], hit: "Lower threshold, faster settling. She knows. She still ran twice.", miss: "She ran first. She knows it helps. She still ran twice." },
      { id: "door", mechanic: "dont-tap", instruction: "Shoes are by the door. Do not tap ‘tomorrow’.", seconds: 5, who: "priya", mood: "anxious", prop: "door", options: [{ id: "tomorrow", label: "Tomorrow instead" }], hit: "Out the door. Every session is a start threshold, met daily.", miss: "Tomorrow. A routine is a starting problem repeated every day." },
      { id: "why-hard", mechanic: "tap", instruction: "If it helps this much, why is it hard to keep?", seconds: 7, who: "priya", mood: "thinking", options: [{ id: "discipline", label: "Not enough discipline" }, { id: "starting", label: "It is a starting problem", correct: true }], hit: "Not discipline. Starting, which is the ADHD difficulty.", miss: "Priya is not short of discipline. Each session starts from nothing." },
      { id: "appointment", mechanic: "order", instruction: "Make the session start itself. Tap in order.", seconds: 8, who: "priya", mood: "pleased", prop: "calendar", options: [{ id: "slot", label: "A time and a place in the calendar" }, { id: "person", label: "One person expecting you" }, { id: "kit", label: "Kit laid out the night before" }], hit: "Three things the routine supplies so you do not have to.", miss: "Slot, person, kit. The routine does the starting." },
      { id: "kit", mechanic: "drag-capture", instruction: "Tonight. Drag the kit to the door.", seconds: 6, who: "priya", mood: "neutral", prop: "door", items: ["Shoes and kit"], hit: "By the door, the morning has one fewer decision.", miss: "In the drawer, the morning starts from nothing." },
      { id: "layers", mechanic: "sort", instruction: "What kept the run going in March? Sort each into its layer.", seconds: 10, who: "priya", mood: "pleased", options: [{ id: "friend", label: "A friend at the park", layer: "people" }, { id: "slot", label: "A fixed 7am slot", layer: "environment" }, { id: "sleep", label: "Early nights", layer: "body" }], hit: "The routine supplied the start. Priya supplied the running.", miss: "The friend is people, the slot is environment, the early nights are body." },
      { id: "your-stops", mechanic: "pick-bean", instruction: "What stops it?", seconds: 10, who: "priya", mood: "embarrassed", writes: { question: "stops", multi: true }, options: [{ id: "starting", label: "Getting out the door", bean: "priya" }, { id: "time", label: "Time", bean: "maya" }, { id: "alone", label: "Doing it alone", bean: "jordan" }, { id: "boredom", label: "Boredom", bean: "alex" }], hit: "Noted. The appointment is built for exactly that.", miss: "Noted. The appointment is built for exactly that." },
    ],
    insight: insightOf("exercise"),
    strategy: strategyOf("exercise", "movement-appointment"),
    next: nextOf("exercise"),
  },
];

const BY_ID: ReadonlyMap<string, Run> = new Map(RUNS.map((r) => [r.id, r]));

export function runFor(id: string): Run | undefined {
  return BY_ID.get(id);
}
