// AR4: the coverage document generates itself, never by hand.
//
// `docs/AESTHETIC-COVERAGE.md` is produced ENTIRELY by `generateCoverageDoc` below, which reads
// only `taste-register.ts`'s own exports — no filesystem access, the same filesystem-free choice
// AR1/AR2/AR3 made for the register itself. That choice matters here for a second reason: it keeps
// this module (and the script that calls it, `scripts/generate-aesthetic-coverage.mts`) resolvable
// by Node's native ESM loader without a bundler. `e2e/site-routes.ts` and
// `src/compliance/public-surfaces.ts` — the live, filesystem-derived route lists AR3's own gate
// checks against — import each other and `@/messaging/templates` without file extensions or via
// the `@/*` alias, which only a bundler (Next.js, vitest/Vite) resolves; a plain `node
// scripts/generate-aesthetic-coverage.mts` run hits Node's stricter ESM resolver and cannot load
// them (confirmed: `ERR_MODULE_NOT_FOUND` on `../src/compliance/surfaces`). `audit-gate.mts` solved
// the same problem for W53 by keeping its whole import graph extension-explicit; this module does
// the same by depending on nothing but the register.
//
// The consequence is scope, stated rather than hidden: this document renders each rule's
// DECLARED `routeScope` and the register's own `ROUTE_COVERAGE_EXEMPTIONS`, not a live recomputed
// union against the filesystem's current route list — that live check is AR3's own job, already
// gated in `taste-register.test.ts` (`checkRouteCoverage` against `ALL_PAGE_ROUTES`, clean today).
// This document is the register made readable, not a second copy of AR3's gate.

import { ROUTE_COVERAGE_EXEMPTIONS, TASTE_RULES, type TasteRule, type TasteSection } from "./taste-register.ts";

const SECTION_ORDER: readonly { key: TasteSection; title: string }[] = [
  { key: "layout", title: "Layout" },
  { key: "type-colour", title: "Type & colour" },
  { key: "interaction", title: "Interaction" },
  { key: "motion", title: "Motion" },
  { key: "honesty", title: "Honesty gates" },
  { key: "review-procedure", title: "Review procedure" },
];

function describeRouteScope(rule: TasteRule): string {
  const scope = rule.routeScope;
  if (!scope) return "—";
  if (scope.kind === "not-route-based") return `not route-based — ${scope.reason}`;
  if (scope.kind === "single-route") return `single route: \`${scope.route}\``;
  return `route sweep: \`${scope.sweep}\``;
}

function renderRule(rule: TasteRule): string {
  const lines = [`### \`${rule.id}\``, "", rule.statement, "", `- **Incident:** ${rule.incident}`];
  if (rule.enforcedBy) {
    lines.push("- **Enforced by:**");
    for (const entry of rule.enforcedBy) lines.push(`  - \`${entry}\``);
  } else {
    lines.push(`- **Unenforced:** ${rule.unenforced}`);
  }
  lines.push(`- **Route scope:** ${describeRouteScope(rule)}`, "");
  return lines.join("\n");
}

/**
 * Render the whole coverage document from a register (defaulting to the real `TASTE_RULES`) and
 * an exemption map (defaulting to the real `ROUTE_COVERAGE_EXEMPTIONS`). Every count below is
 * computed from the `register` argument passed in, never hand-typed, so a mutated register (the
 * test's own non-vacuity check) produces a document whose numbers actually change.
 */
export function generateCoverageDoc(
  register: readonly TasteRule[] = TASTE_RULES,
  exemptions: Readonly<Record<string, string>> = ROUTE_COVERAGE_EXEMPTIONS,
): string {
  const enforced = register.filter((r) => r.enforcedBy);
  const unenforced = register.filter((r) => r.unenforced);
  const exemptionEntries = Object.entries(exemptions).sort(([a], [b]) => a.localeCompare(b));

  const lines: string[] = [
    "# Aesthetic coverage",
    "",
    "> Generated by `scripts/generate-aesthetic-coverage.mts` from `src/design/taste-register.ts`" +
      " via `generateCoverageDoc` (`src/design/taste-coverage-doc.ts`). Do not hand-edit —" +
      " `taste-coverage-doc.test.ts` regenerates this file in memory on every run and fails the" +
      " build the moment the two disagree (AR4, W207's shape: staleness is a failing test, not a" +
      " review finding).",
    "",
    "## Summary",
    "",
    `- **${register.length} rules** across ${SECTION_ORDER.length} sections`,
    `- **${enforced.length} enforced**, **${unenforced.length} unenforced**`,
    `- **${exemptionEntries.length} route exemption${exemptionEntries.length === 1 ? "" : "s"}** declared` +
      " (routes no enforced rule's declared scope reaches; see below)",
    "",
  ];

  for (const section of SECTION_ORDER) {
    const rules = register.filter((r) => r.section === section.key).slice().sort((a, b) => a.id.localeCompare(b.id));
    if (rules.length === 0) continue;
    lines.push(`## ${section.title}`, "");
    for (const rule of rules) lines.push(renderRule(rule));
  }

  lines.push(
    "## Route coverage exemptions",
    "",
    "Routes no enforced rule's declared scope reaches, named with a reason rather than silently" +
      " passing as covered (AR3). This lists the register's own declared exemptions; the live" +
      " check against the filesystem's current route list runs in `taste-register.test.ts`.",
    "",
  );
  if (exemptionEntries.length === 0) {
    lines.push("None declared.", "");
  } else {
    for (const [route, reason] of exemptionEntries) lines.push(`- \`${route}\` — ${reason}`, "");
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}
